[package]
name = "ember_driver"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
ember_span.workspace = true
ember_diag.workspace = true
ember_lexer.workspace = true
ember_ast.workspace = true
ember_parser.workspace = true
ember_types.workspace = true
ember_typeck.workspace = true
ember_hir.workspace = true
ember_mir.workspace = true
ember_codegen_c.workspace = true
ember_build.workspace = true

[lints]
workspace = true

[[bin]]
name = "ember"
path = "src/main.rs"
