[package]
name = "ember_typeck"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
ember_branding.workspace = true
ember_span.workspace = true
ember_diag.workspace = true
ember_ast.workspace = true
ember_types.workspace = true
ember_hir.workspace = true

[lints]
workspace = true
