"""What each benchmark program does, as the README's tables say it, and the footnote mark a row
carries (README notes ¹ and ² for the rows where MSVC turns the hand-written C's loops around,
³ for what gcc does to Ember's recursion). Every program in `programs/` has a line here."""

DESC = {
    't1b_str_loop': 'Add up the characters of a 3 MB text, 20 times: `for c in text`',
    't1_chars': 'Add up the characters of a 3 MB text, 20 times: `for c in text.chars()`',
    't2_bytes': 'Add up the bytes of a 3 MB text, 20 times: `for b in text.bytes()`',
    't3_lines': 'Count the lines of a 3 MB text and their lengths, 200 times: `text.lines()`',
    't4_split': 'Split a 3 MB text at its commas, counting the parts and their lengths, 200 times: `text.split(",")`',
    't5_words': 'Count the words of a 3 MB text and their lengths, 20 times: `text.split_whitespace()`',
    't6_char_indices': 'Mix each character of a 3 MB text with its byte offset, 20 times: `text.char_indices()`',
    'a04_map_int': 'Map of numbers: 1 million inserts, then 5 million lookups',
    'a03_strings': 'Build a long string (16 million appends), then count one letter in it',
    'p2_view_held': 'Copy a 1,000-number list into another, one item at a time, 100,000 times',
    'a11_dod_soa': 'Two lists of 100,000 decimal numbers, add one into the other 5,000 times',
    'a00_empty': 'Start and stop an empty program',
    'a02_float_math': 'Decimal arithmetic: the Mandelbrot set, 1,000 × 1,000 points',
    'p5_million_objects': '1 million objects with a name and a list, each read 40 times',
    'p4_views_alive_01': 'Clear and refill a list while 1 other list is being viewed',
    'p4_views_alive_04': 'Clear and refill a list while 4 other lists are being viewed',
    'p4_views_alive_16': 'Clear and refill a list while 16 other lists are being viewed',
    'w1_sum_loop': 'Add up a list of 1,000 numbers, 300,000 times, overflow checks off',
    'p1_read_loop': 'Add up a list of 1,000 numbers, 300,000 times, overflow checks on',
    'b13_checked': 'Add one list into another, 2,000 rounds, overflow checks on',
    'b13_wrapped': 'Add one list into another, 2,000 rounds, overflow checks off',
    'b14_checked': 'Change every number using a second list, 20,000 rounds, overflow checks on',
    'b14_wrapped': 'Change every number using a second list, 20,000 rounds, overflow checks off',
    'b15_checked': 'Change every number twice, reading back what it wrote, overflow checks on',
    'b15_wrapped': 'Change every number twice, reading back what it wrote, overflow checks off',
    'b16_checked': 'Change every number twice, writing to a separate list, overflow checks on',
    'b16_wrapped': 'Change every number twice, writing to a separate list, overflow checks off',
    'w13_int_lanes': 'Add two lists plus the round number into a third, overflow checks off',
    'w13_checked': 'Add two lists plus the round number into a third, overflow checks on',
    'a06_enum_match': 'Enum with `match`: area of 1 million shapes, 100 times',
    'a01_int_math': 'Integer arithmetic: 50 million rounds of multiply, divide and remainder',
    'a07_virtual_calls': 'Calls through an interface: area of 1 million shapes, 20 times',
    'a08_closures': 'Call a function passed as a value, 200 million times',
    'a09_generics': 'A generic function ("larger of two"), 200 million times',
    'a05_structs': 'Move 100,000 particles 2,000 times, changing each in place',
    'a10_recursion': 'Recursion: Fibonacci of 38, the slow way',
    'a12_sort': 'Sort 5 million numbers',
    'a13_map_scrambled': 'Map of numbers in no order (scrambled keys): 1 million inserts, then 5 million lookups',
    'a14_map_gap_1024': 'Map of numbers 1,024 apart: 1 million inserts, then 5 million lookups',
    'a15_map_gap_1048576': 'Map of numbers 1,048,576 apart: 1 million inserts, then 5 million lookups',
    'a16_map_text': 'Map of text keys ("key0", "key1", …): 200,000 inserts, then 1 million lookups',
    'p6_million_objects_6_lists': '1 million objects holding 6 lists, each read 40 times',
    'p3_mut_self_1_field': 'Call a method that changes an object taken from a list, 100 million times (object holding 1 list)',
    'p3_mut_self_6_fields': 'Call a method that changes an object taken from a list, 100 million times (object holding 6 lists)',
    'p7_mut_self_calls_a_function': 'Call a method that changes an object taken from a list, and the method calls another function, 100 million times',
    's1_enumerate_xor': 'Number each item of a 1-million-number list while changing it (`enumerate`), 300 times',
    's2_zip_and': 'Walk two 1-million-number lists side by side, changing one (`zip`), 300 times',
    's3_skip_step_take': 'Every third number of a list, after skipping some, at most 300,000 of them (`skip`, `step_by`, `take`), 300 times',
    's4_copied_enumerate_skip': 'Number the items of a list past a starting point, as copies (`copied`, `enumerate`, `skip`), 300 times',
    's5_range_step_enumerate': 'Number every second value of a range of 2 million (`step_by`, `enumerate`), 300 times',
}

MARKS = {
    'b13_checked': ' ¹',
    'b13_wrapped': ' ¹',
    'b14_checked': ' ²',
    'b14_wrapped': ' ²',
    'b15_checked': ' ²',
    'b15_wrapped': ' ²',
    'b16_checked': ' ²',
    'b16_wrapped': ' ²',
    'a11_dod_soa': ' ²',
    'a10_recursion': ' ³',
}
