//! The public C surface of one emitted package (`[FFI-26]`). Names and
//! declarators come from the same emitter and type plan as the C translation
//! unit, while the dependency walk limits this header to exported types.

use super::{Definition, Emitter, HeaderOutput, TypeNode};
use ember_mir::Body;
use ember_types::{Ty, TyKind, IntTy, UintTy};
use std::collections::BTreeSet;

pub(super) fn render(emitter: &Emitter<'_>, bodies: &[Body], package_name: &str) -> Result<HeaderOutput, String> {
    let exports: Vec<&Body> = bodies.iter()
        .filter(|body| body.abi.as_deref() == Some("C")
            && !body.is_extern_declaration && !body.is_abstract)
        .collect();
    let mut reachable = Reachable::new(emitter);
    for body in &exports {
        reachable.visit(body.return_ty())?;
        for (_, parameter) in body.args() {
            reachable.visit(parameter.ty)?;
        }
    }

    // Hex of the exact UTF-8 bytes is injective: e.g. foo-bar, foo_bar and
    // differently spelled Unicode names must never suppress each other.
    let mut base_guard = String::from("EMBER_GENERATED_HEADER_");
    for byte in package_name.as_bytes() {
        base_guard.push_str(&format!("{byte:02X}"));
    }
    base_guard.push_str("_H");
    let mut guard = base_guard.clone();
    let mut suffix = 2;
    while exports.iter().any(|body| body.symbol == guard)
        || emitter.order.iter().any(|node| emitter.node_name(*node) == guard)
        || reachable.opaque.contains(&guard) {
        guard = format!("{base_guard}_{suffix}");
        suffix += 1;
    }

    let mut out = String::new();
    line(&mut out, "/* Generated by Ember. C ABI declarations for package exports. */");
    line(&mut out, &format!("#ifndef {guard}"));
    line(&mut out, &format!("#define {guard}"));
    line(&mut out, "#include <stdbool.h>");
    line(&mut out, "#include <stddef.h>");
    line(&mut out, "#include <stdint.h>");
    if reachable.runtime_integer_carrier {
        line(&mut out, &format!("#include \"{}_runtime/{}\"",
            ember_branding::SYMBOL_PREFIX, ember_branding::runtime_header()));
    }
    line(&mut out, "");
    line(&mut out, "#ifdef __cplusplus");
    line(&mut out, "extern \"C\" {");
    line(&mut out, "#endif");

    for opaque in &reachable.opaque {
        line(&mut out, &format!("struct {opaque};"));
    }
    let plan: Vec<_> = emitter.order.iter().copied()
        .filter(|node| reachable.nodes.contains(node))
        .map(|node| (emitter.node_name(node), emitter.definition(node)))
        .collect();
    if !plan.is_empty() {
        line(&mut out, "");
        for (name, definition) in &plan {
            if matches!(definition, Definition::Struct(_)) {
                line(&mut out, &format!("typedef struct {name} {name};"));
            }
        }
        for (name, definition) in &plan {
            match definition {
                Definition::Alias(underlying) => line(&mut out, &format!("typedef {underlying} {name};")),
                Definition::FnPointer { ret, args } =>
                    line(&mut out, &format!("typedef {ret} (*{name})({args});")),
                Definition::Struct(members) => {
                    line(&mut out, &format!("struct {name} {{"));
                    if members.is_empty() { line(&mut out, "    char _empty;"); }
                    for member in members { line(&mut out, &format!("    {member};")); }
                    line(&mut out, "};");
                }
            }
        }
    }
    if !exports.is_empty() { line(&mut out, ""); }
    for body in exports {
        line(&mut out, &format!("/* threads: {} */", body.export_thread_policy.as_str()));
        line(&mut out, &format!("{};", emitter.signature(body)));
    }
    line(&mut out, "");
    line(&mut out, "#ifdef __cplusplus");
    line(&mut out, "}");
    line(&mut out, "#endif");
    line(&mut out, &format!("#endif /* {guard} */"));
    Ok(HeaderOutput { source: out, needs_runtime_header: reachable.runtime_integer_carrier })
}

fn line(out: &mut String, value: &str) {
    out.push_str(value);
    out.push('\n');
}

struct Reachable<'a, 'b> {
    emitter: &'a Emitter<'b>,
    seen: BTreeSet<Ty>,
    nodes: BTreeSet<TypeNode>,
    opaque: BTreeSet<String>,
    runtime_integer_carrier: bool,
}

impl<'a, 'b> Reachable<'a, 'b> {
    fn new(emitter: &'a Emitter<'b>) -> Self {
        Self { emitter, seen: BTreeSet::new(), nodes: BTreeSet::new(),
            opaque: BTreeSet::new(), runtime_integer_carrier: false }
    }

    fn visit(&mut self, ty: Ty) -> Result<(), String> {
        if !self.seen.insert(ty) { return Ok(()); }
        match self.emitter.types.kind(ty).clone() {
            TyKind::Int(IntTy::I128) | TyKind::Uint(UintTy::U128) => {
                self.runtime_integer_carrier = true;
            }
            TyKind::Struct(id) => {
                if !self.emitter.types.is_ffi_safe(ty) || self.emitter.types.needs_drop(ty) {
                    return Err(self.unsupported(ty));
                }
                self.nodes.insert(TypeNode::Struct(id));
                let fields = self.emitter.types.struct_def(id).fields.iter().map(|field| field.ty).collect::<Vec<_>>();
                for field in fields { self.visit(field)?; }
            }
            TyKind::Enum(id) => {
                if !self.emitter.types.is_ffi_safe(ty) { return Err(self.unsupported(ty)); }
                self.nodes.insert(TypeNode::Enum(id));
                let def = self.emitter.types.enum_def(id);
                let repr = def.repr;
                let fields = def.variants.iter().flat_map(|variant|
                    variant.fields.iter().map(|field| field.ty)).collect::<Vec<_>>();
                self.visit(repr)?;
                for field in fields { self.visit(field)?; }
            }
            TyKind::Fn { params, ret, abi, .. } => {
                if !abi.as_ref().is_some_and(|name| name.is("C")) {
                    return Err(self.unsupported(ty));
                }
                self.nodes.insert(TypeNode::Structural(ty));
                for param in params { self.visit(param.ty)?; }
                self.visit(ret)?;
            }
            TyKind::Array { elem, .. } => {
                self.nodes.insert(TypeNode::Structural(ty));
                self.visit(elem)?;
            }
            TyKind::Ptr { inner, .. } | TyKind::Ref { inner, .. } => self.visit(inner)?,
            TyKind::Opaque(name) => {
                self.opaque.insert(name.as_str().rsplit('.').next().unwrap_or(name.as_str()).to_string());
            }
            TyKind::Bool | TyKind::Char | TyKind::Int(_) | TyKind::Uint(_)
            | TyKind::Float(_) | TyKind::Void | TyKind::Never | TyKind::CStr => {}
            _ => return Err(self.unsupported(ty)),
        }
        Ok(())
    }

    fn unsupported(&self, ty: Ty) -> String {
        format!("cannot emit C export header: reachable type `{}` has no supported public C declaration",
            self.emitter.types.symbol_name(ty))
    }
}
