//! The C11 backend: MIR to C (Part XVIII §6).
//!
//! `[CG-C-1]` — the emitted C must compile warning-free under
//! `-std=c11 -Wall -Wextra` and `/W3`, be free of undefined behaviour by
//! construction, and depend on no compiler extension except through
//! `ember_rt.h` macros that have portable fallbacks.
//!
//! `[CG-C-2]` — the output is deterministic for identical input: ordering is
//! stable and nothing is keyed on a pointer, so the build cache and
//! `diff`-based review both work.

use std::fmt::Write as _;

use ember_mir::{
    AggregateKind, AssertKind, Body, Builtin, CastKind, Const, FuncRef, LocalKind, Operand, Place,
    Projection, RETURN_LOCAL, Rvalue, Stmt, StmtKind, Terminator,
};
use std::path::MAIN_SEPARATOR;

use ember_span::SourceMap;
use ember_types::{EnumId, FloatTy, IntTy, StructId, Ty, TyKind, TypeTable, UintTy};
use std::collections::{BTreeMap, BTreeSet};

pub struct Output {
    /// The single translation unit for this module.
    pub c_source: String,
}

pub fn emit(
    bodies: &[Body],
    types: &TypeTable,
    map: &SourceMap,
    module_name: &str,
    has_main: bool,
) -> Output {
    let (order, structural) = plan_types(types);
    let usize_ty = types
        .all()
        .find(|(_, k)| matches!(k, TyKind::Uint(UintTy::Usize)))
        .map(|(ty, _)| ty)
        .or_else(|| types.all().next().map(|(ty, _)| ty))
        .expect("the interner always holds the common types");
    let mut emitter = Emitter {
        types,
        map,
        out: String::new(),
        line_directives: true,
        order,
        structural,
        usize_ty,
    };
    emitter.emit_module(bodies, module_name, has_main);
    Output { c_source: emitter.out }
}

struct Emitter<'a> {
    types: &'a TypeTable,
    map: &'a SourceMap,
    out: String,
    line_directives: bool,
    /// Every type definition to emit, in an order where a type is defined
    /// after everything it contains by value.
    order: Vec<TypeNode>,
    /// The generated C name of each tuple and fixed-array type.
    structural: BTreeMap<Ty, String>,
    /// `usize`, for the lengths inside an `Array[T]`. The emitter has no
    /// `CommonTypes`, so it finds the one the interner already holds.
    usize_ty: Ty,
}

/// Where a projection walk has reached: a type, plus the variant a
/// `Downcast` selected, which the `Field` after it needs.
#[derive(Clone, Copy)]
struct Cursor {
    ty: Ty,
    variant: Option<usize>,
}

/// How one type is written in C: a `struct` with members, or a name for
/// another type.
enum Definition {
    Struct(Vec<String>),
    Alias(String),
}

/// A C type definition: either a named Ember struct or a generated struct
/// standing in for a tuple or a fixed array.
///
/// C has no tuple, and a bare C array cannot be assigned, passed or returned
/// by value — but an Ember tuple and an Ember `[T; N]` are ordinary values
/// (Part IV.3). Wrapping both in a generated struct gives them C's value
/// semantics for free, with the same layout, and leaves every copy, argument
/// and return path in this backend unchanged.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
enum TypeNode {
    Struct(StructId),
    Enum(EnumId),
    Structural(Ty),
}

impl Emitter<'_> {
    fn line(&mut self, text: &str) {
        self.out.push_str(text);
        self.out.push('\n');
    }

    fn emit_module(&mut self, bodies: &[Body], module_name: &str, has_main: bool) {
        self.line("/* Generated by the Ember compiler. Do not edit. */");
        self.line(&format!("/* module: {module_name} */"));
        self.line("");
        self.line("#include \"ember_rt.h\"");
        self.line("");

        self.emit_type_declarations();
        self.emit_prototypes(bodies);

        for body in bodies {
            self.emit_body(body);
        }

        if has_main {
            self.emit_entry_point();
        }
    }

    /// `ember_types.h`'s content, inlined into the single translation unit
    /// Phase 0 emits. Structs are declared in the order they were interned,
    /// which is declaration order, so a struct's fields are always already
    /// complete types.
    fn emit_type_declarations(&mut self) {
        let plan: Vec<(String, Definition)> = self
            .order
            .clone()
            .into_iter()
            .map(|node| (self.node_name(node), self.definition(node)))
            .collect();

        if plan.is_empty() {
            return;
        }
        self.line("/* types */");
        // Every struct is forward-declared, so one may hold a pointer to
        // another defined later. An alias is complete where it stands.
        for (name, definition) in &plan {
            if matches!(definition, Definition::Struct(_)) {
                self.line(&format!("typedef struct {name} {name};"));
            }
        }
        for (name, definition) in &plan {
            match definition {
                Definition::Alias(underlying) => {
                    self.line(&format!("typedef {underlying} {name};"));
                }
                Definition::Struct(members) => {
                    self.line(&format!("struct {name} {{"));
                    if members.is_empty() {
                        // `[STR-4]` — a zero-sized struct is legal in Ember but
                        // not in C, so it gets a padding byte. Its size is
                        // never observed through the C type.
                        self.line("    char _empty;");
                    }
                    for member in members {
                        self.line(&format!("    {member};"));
                    }
                    self.line("};");
                }
            }
        }
        self.line("");
    }

    fn node_name(&self, node: TypeNode) -> String {
        match node {
            TypeNode::Struct(id) => format!("em_{}", self.types.struct_def(id).name),
            TypeNode::Enum(id) => format!("em_{}", self.types.enum_def(id).name),
            TypeNode::Structural(ty) => self.structural_name(ty),
        }
    }

    /// What one type definition looks like in C. Members are already written
    /// as declarators — an array member interleaves its type and its name, so
    /// this cannot be a `(type, name)` pair.
    fn definition(&self, node: TypeNode) -> Definition {
        match node {
            TypeNode::Struct(id) => Definition::Struct(
                self.types
                    .struct_def(id)
                    .fields
                    .iter()
                    .map(|f| format!("{} {}", self.c_type(f.ty), f.name))
                    .collect(),
            ),
            // `[ENM-3]` — a unit-only enum *is* its discriminant, so it is a
            // name for the repr integer and nothing more. `[TYP-12]` — a
            // payload enum is `{tag, union of variants}`.
            TypeNode::Enum(id) => {
                let def = self.types.enum_def(id);
                if def.is_unit_only() {
                    return Definition::Alias(self.c_type(def.repr));
                }
                let mut members = vec![format!("{} tag", self.c_type(def.repr))];
                let mut union = vec!["union {".to_string()];
                for variant in def.variants.iter().filter(|v| !v.fields.is_empty()) {
                    let fields: Vec<String> = variant
                        .fields
                        .iter()
                        .map(|f| format!("{} {}; ", self.c_type(f.ty), f.name))
                        .collect();
                    union.push(format!("        struct {{ {}}} {};", fields.concat(), variant.name));
                }
                union.push("    } payload".to_string());
                members.push(union.join("\n"));
                Definition::Struct(members)
            }
            TypeNode::Structural(ty) => Definition::Struct(match self.types.kind(ty) {
                TyKind::Tuple(items) => items
                    .iter()
                    .enumerate()
                    .map(|(i, &item)| format!("{} _{i}", self.c_type(item)))
                    .collect(),
                // `[T; 0]` is legal in Ember; a zero-length array is not legal
                // C, so the member is padded to one element the same way an
                // empty struct is.
                TyKind::Array { elem, len } => {
                    vec![format!("{} _0[{}]", self.c_type(*elem), (*len).max(1))]
                }
                _ => Vec::new(),
            }),
        }
    }

    /// The element type of an `Array[T]`, given the receiver's type — which
    /// may be a `ref mut Array[T]`, because `push` takes the receiver by
    /// reference.
    fn element_of(&self, ty: Ty) -> Ty {
        match self.types.kind(ty) {
            TyKind::Vec { elem } => *elem,
            TyKind::Ref { inner, .. } | TyKind::Ptr { inner, .. } => self.element_of(*inner),
            _ => ty,
        }
    }

    /// The generated name of a tuple or fixed-array type.
    ///
    /// `plan_types` walks every interned type, so a missing name is a bug in
    /// this backend rather than anything a program can cause — and a silent
    /// `void*` here would produce C that compiles and computes the wrong
    /// thing, so it fails loudly instead.
    fn structural_name(&self, ty: Ty) -> String {
        match self.structural.get(&ty) {
            Some(name) => name.clone(),
            None => panic!("no generated C type for `{}`", self.types.display(ty)),
        }
    }

    fn emit_prototypes(&mut self, bodies: &[Body]) {
        if bodies.is_empty() {
            return;
        }
        self.line("/* prototypes */");
        for body in bodies {
            let signature = self.signature(body);
            self.line(&format!("static {signature};"));
        }
        self.line("");
    }

    fn signature(&self, body: &Body) -> String {
        let ret = self.c_type(body.return_ty());
        let params: Vec<String> = body
            .args()
            .map(|(id, decl)| format!("{} _{}", self.c_type(decl.ty), id.0))
            .collect();
        let params = if params.is_empty() { "void".to_string() } else { params.join(", ") };
        format!("{ret} {}({params})", body.symbol)
    }

    fn emit_body(&mut self, body: &Body) {
        let signature = self.signature(body);
        self.line(&format!("static {signature} {{"));

        // Locals. Parameters are already C parameters; the return slot and
        // every other local are declared here.
        for (index, decl) in body.locals.iter().enumerate() {
            if decl.kind == LocalKind::Arg {
                continue;
            }
            if self.is_void(decl.ty) {
                continue;
            }
            let comment = match &decl.name {
                Some(name) => format!("  /* {name} */"),
                None => String::new(),
            };
            self.line(&format!("    {} _{index};{comment}", self.c_type(decl.ty)));
        }
        if body.locals.iter().any(|d| d.kind != LocalKind::Arg && !self.is_void(d.ty)) {
            self.line("");
        }

        // A pattern may bind a payload the arm never reads — `Circle(r): return 1`
        // is legal Ember — and the assignment that binds it then trips
        // `-Wunused-but-set-variable`. `[CG-C-1]` requires warning-free output,
        // so each such local is discarded once, explicitly.
        // A `void` local is never declared, so it cannot be discarded either.
        let unread: Vec<usize> = unread_locals(body)
            .into_iter()
            .filter(|index| !self.is_void(body.locals[*index].ty))
            .collect();
        if !unread.is_empty() {
            let discards: Vec<String> =
                unread.iter().map(|index| format!("(void)_{index};")).collect();
            self.line(&format!("    {}", discards.join(" ")));
            self.line("");
        }

        // Only blocks something actually jumps to get a label: an unreferenced
        // label is a warning under `-Wall` and MSVC's C4102, and `[CG-C-1]`
        // requires the emitted C to compile without warnings.
        let referenced = referenced_blocks(body);
        for (index, block) in body.blocks.iter().enumerate() {
            if referenced.contains(&index) {
                // A label with no statement after it is a syntax error in C,
                // so every label is followed by at least `;`.
                self.line(&format!("bb{index}: ;"));
            }
            for stmt in &block.stmts {
                self.emit_stmt(stmt, body);
            }
            self.emit_terminator(&block.terminator, body, index);
        }

        self.line("}");
        self.line("");
    }

    fn emit_stmt(&mut self, stmt: &Stmt, body: &Body) {
        match &stmt.kind {
            StmtKind::Assign { place, rvalue } => {
                let ty = self.place_ty(place, body);
                if self.is_void(ty) {
                    return;
                }
                self.emit_line_directive(stmt.span);
                let lhs = self.place_in(place, body);
                // `[value; count]` fills the array with a loop rather than
                // `count` copies of the operand's text, so a large array costs
                // one statement here and one in the emitted C.
                if let Rvalue::Repeat { value, count } = rvalue {
                    let value = self.operand(value, body);
                    self.line(&format!(
                        "    for (size_t _i = 0; _i < {count}u; ++_i) {{ {lhs}._0[_i] = {value}; }}"
                    ));
                    return;
                }
                let rhs = self.rvalue(rvalue, body, ty);
                self.line(&format!("    {lhs} = {rhs};"));
            }
            StmtKind::CheckedBinaryOp { dest, overflow, op, lhs, rhs } => {
                // `bool ember_ck_add_i32(a, b, &dest)` returns whether the
                // operation overflowed and writes the wrapped result either
                // way, so the value is defined on both paths.
                let ty = self.place_ty(dest, body);
                let helper = format!("ember_ck_{}_{}", checked_name(*op), self.checked_suffix(ty));
                self.emit_line_directive(stmt.span);
                self.line(&format!(
                    "    {} = {helper}({}, {}, &{});",
                    self.place_in(overflow, body),
                    self.operand(lhs, body),
                    self.operand(rhs, body),
                    self.place_in(dest, body)
                ));
            }
            // Storage markers carry no code in C; the borrow checker and drop
            // elaboration consume them before this point.
            StmtKind::StorageLive(_) | StmtKind::StorageDead(_) | StmtKind::Nop => {}
        }
    }

    /// `#line` maps every emitted statement back to its Ember source
    /// (Part XVIII §6, "Debug info").
    fn emit_line_directive(&mut self, span: ember_span::Span) {
        if !self.line_directives || span.is_dummy() || self.map.get(span.file).is_none() {
            return;
        }
        let file = self.map.file(span.file);
        let line = file.line_of(span.start);
        // Forward slashes: a backslash in a `#line` path is an escape.
        let path = file.path.display().to_string().replace(MAIN_SEPARATOR, "/");
        let _ = writeln!(self.out, "#line {line} \"{path}\"");
    }

    fn emit_terminator(&mut self, terminator: &Terminator, body: &Body, index: usize) {
        match terminator {
            Terminator::Goto(target) => {
                // A jump to the next block in order is a fallthrough.
                if target.0 as usize == index + 1 {
                    self.line("    /* fallthrough */");
                } else {
                    self.line(&format!("    goto bb{};", target.0));
                }
            }
            Terminator::SwitchInt { discr, targets, otherwise } => {
                let discr = self.operand(discr, body);
                // Phase 0 only produces two-way branches on a boolean.
                if let [(value, target)] = targets.as_slice() {
                    self.line(&format!(
                        "    if ({discr} == {value}) {{ goto bb{}; }} else {{ goto bb{}; }}",
                        target.0, otherwise.0
                    ));
                } else {
                    self.line(&format!("    switch ({discr}) {{"));
                    for (value, target) in targets {
                        self.line(&format!("    case {value}: goto bb{};", target.0));
                    }
                    self.line(&format!("    default: goto bb{};", otherwise.0));
                    self.line("    }");
                }
            }
            Terminator::Assert { cond, expected, msg, next, span } => {
                let cond = self.operand(cond, body);
                let negate = if *expected { "!" } else { "" };
                let location = self.location(*span);
                let call = match msg {
                    AssertKind::Overflow(op) => {
                        format!("ember_panic_overflow(\"{}\", {location})", op.c_operator())
                    }
                    AssertKind::SignedDivisionOverflow => {
                        format!("ember_panic_overflow(\"/\", {location})")
                    }
                    AssertKind::ShiftTooLarge => {
                        format!("ember_panic_overflow(\"shift\", {location})")
                    }
                    AssertKind::DivisionByZero => format!("ember_panic_div_zero({location})"),
                    AssertKind::Bounds { len, index: at } => format!(
                        "ember_panic_bounds({}, {}, {location})",
                        self.operand(at, body),
                        self.operand(len, body)
                    ),
                };
                self.line(&format!("    if ({negate}{cond}) {{ {call}; }}"));
                if next.0 as usize == index + 1 {
                    self.line("    /* fallthrough */");
                } else {
                    self.line(&format!("    goto bb{};", next.0));
                }
            }
            Terminator::Return => {
                if self.is_void(body.return_ty()) {
                    self.line("    return;");
                } else {
                    self.line("    return _0;");
                }
            }
            Terminator::Unreachable => {
                self.line("    EMBER_UNREACHABLE();");
            }
            Terminator::Call { func, args, dest, next } => {
                let call = self.call_expression(func, args, body);
                let dest_ty = self.place_ty(dest, body);
                if self.is_void(dest_ty) {
                    self.line(&format!("    {call};"));
                } else {
                    let dest_text = self.place_in(dest, body);
                    self.line(&format!("    {dest_text} = {call};"));
                }
                if next.0 as usize == index + 1 {
                    self.line("    /* fallthrough */");
                } else {
                    self.line(&format!("    goto bb{};", next.0));
                }
            }
        }
    }

    /// An `ember_loc` for a panic, from the span of the operation itself.
    fn location(&self, span: ember_span::Span) -> String {
        if span.is_dummy() || self.map.get(span.file).is_none() {
            return "ember_loc_unknown()".to_string();
        }
        let file = self.map.file(span.file);
        let lc = file.line_col(span.start);
        let path = file.path.display().to_string().replace('\\', "/");
        format!("ember_loc_at({}, {}, {})", c_string_literal(&path), lc.line, lc.col)
    }

    /// The `ember_ck_*` suffix for a type: the helpers are per width and
    /// signedness.
    fn checked_suffix(&self, ty: ember_types::Ty) -> String {
        match self.types.kind(ty) {
            TyKind::Int(i) => match i {
                IntTy::I8 => "i8",
                IntTy::I16 => "i16",
                IntTy::I32 => "i32",
                IntTy::I64 => "i64",
                IntTy::I128 => "i64",
                IntTy::Isize => "isize",
            },
            TyKind::Uint(u) => match u {
                UintTy::U8 => "u8",
                UintTy::U16 => "u16",
                UintTy::U32 => "u32",
                UintTy::U64 => "u64",
                UintTy::U128 => "u64",
                UintTy::Usize => "usize",
            },
            _ => "i64",
        }
        .to_string()
    }

    fn call_expression(&self, func: &FuncRef, args: &[Operand], body: &Body) -> String {
        let rendered: Vec<String> = args.iter().map(|a| self.operand(a, body)).collect();
        match func {
            FuncRef::Direct { symbol } => format!("{symbol}({})", rendered.join(", ")),
            FuncRef::Builtin { which, arg_ty } => {
                // `Array` and `String` share one runtime buffer; the element
                // size is passed at each call, which is how a single
                // implementation serves every element type.
                match which {
                    Builtin::ArrayNew | Builtin::StringNew => {
                        return "ember_vec_empty()".to_string();
                    }
                    Builtin::ArrayPush => {
                        let elem = self.element_of(*arg_ty);
                        return format!(
                            "ember_vec_push({}, sizeof({}), &{})",
                            rendered[0],
                            self.c_type(elem),
                            rendered[1]
                        );
                    }
                    Builtin::StringPush => {
                        return format!(
                            "ember_vec_extend({}, {}.ptr, {}.len)",
                            rendered[0], rendered[1], rendered[1]
                        );
                    }
                    Builtin::ArrayLen | Builtin::StringLen => {
                        return format!("({}).len", rendered[0]);
                    }
                    Builtin::StringAsStr => {
                        return format!("ember_vec_as_str(&{})", rendered[0]);
                    }
                    Builtin::Format => {
                        return format!(
                            "ember_fmt_{}({}, {})",
                            self.format_suffix(*arg_ty),
                            rendered[0],
                            rendered[1]
                        );
                    }
                    Builtin::Println | Builtin::Print => {}
                }
                let suffix = self.builtin_suffix(*arg_ty);
                let name = match which {
                    Builtin::Println => "ember_println",
                    _ => "ember_print",
                };
                format!("{name}_{suffix}({})", rendered.join(", "))
            }
        }
    }

    /// Which `ember_rt` printer a builtin call resolves to. Phase 0 has no
    /// `Display` interface, so the choice is made here from the argument type.
    /// Which `ember_fmt_*` an f-string piece appends through. A `String`
    /// piece is formatted as the `str` it borrows.
    fn format_suffix(&self, ty: Ty) -> &'static str {
        match self.types.kind(ty) {
            TyKind::Vec { .. } => "str",
            _ => self.builtin_suffix(ty),
        }
    }

    fn builtin_suffix(&self, ty: ember_types::Ty) -> &'static str {
        match self.types.kind(ty) {
            TyKind::Bool => "bool",
            TyKind::Char => "char",
            TyKind::Int(_) => "i64",
            TyKind::Uint(_) => "u64",
            TyKind::Float(FloatTy::F64) => "f64",
            TyKind::Float(_) => "f32",
            TyKind::Str => "str",
            _ => "str",
        }
    }

    // -- places, operands, rvalues -------------------------------------------

    fn place_in(&self, place: &Place, body: &Body) -> String {
        let mut out = format!("_{}", place.local.0);
        let mut at = Cursor { ty: body.local(place.local).ty, variant: None };
        for projection in &place.projection {
            match projection {
                Projection::Field(index) => match (at.variant, self.types.kind(at.ty)) {
                    // After a downcast, a field is that variant's payload.
                    (Some(variant), TyKind::Enum(id)) => {
                        let def = self.types.enum_def(*id);
                        let variant = &def.variants[variant];
                        out.push_str(&format!(
                            ".payload.{}.{}",
                            variant.name, variant.fields[*index].name
                        ));
                    }
                    (_, TyKind::Struct(id)) => {
                        let def = self.types.struct_def(*id);
                        out.push_str(&format!(".{}", def.fields[*index].name));
                    }
                    // An `Array[T]` is the runtime's buffer: pointer, length,
                    // capacity, in that order.
                    (_, TyKind::Vec { .. }) => {
                        out.push_str(match index {
                            0 => ".ptr",
                            1 => ".len",
                            _ => ".cap",
                        });
                    }
                    // A tuple's elements are the generated struct's `_0`,
                    // `_1`, … in order.
                    _ => out.push_str(&format!("._{index}")),
                },
                // A fixed array is a generated struct wrapping one C array, so
                // the subscript goes through that member. An `Array[T]` keeps
                // its elements behind a `void*`, so the subscript casts first.
                Projection::Index(local) => match self.types.kind(at.ty) {
                    TyKind::Vec { elem } => {
                        out = format!("(({}*){out}.ptr)[_{}]", self.c_type(*elem), local.0);
                    }
                    _ => out.push_str(&format!("._0[_{}]", local.0)),
                },
                Projection::ConstIndex(i) => match self.types.kind(at.ty) {
                    TyKind::Vec { elem } => {
                        out = format!("(({}*){out}.ptr)[{i}]", self.c_type(*elem));
                    }
                    _ => out.push_str(&format!("._0[{i}]")),
                },
                Projection::Deref => out = format!("(*{out})"),
                // A downcast writes nothing on its own; the `Field` after it
                // names the variant and the member together.
                Projection::Downcast(_) => {}
                Projection::Column(i) => out.push_str(&format!(".col{i}")),
            }
            at = self.project(at, projection);
        }
        out
    }

    fn place_ty(&self, place: &Place, body: &Body) -> Ty {
        let mut at = Cursor { ty: body.local(place.local).ty, variant: None };
        for projection in &place.projection {
            at = self.project(at, projection);
        }
        at.ty
    }

    /// Where one projection arrives. A projection that does not apply to the
    /// type leaves it alone; the type checker has already rejected that
    /// program, and the backend only has to stay on its feet.
    fn project(&self, at: Cursor, projection: &Projection) -> Cursor {
        let plain = |ty| Cursor { ty, variant: None };
        match (projection, self.types.kind(at.ty)) {
            (Projection::Downcast(variant), TyKind::Enum(_)) => {
                Cursor { ty: at.ty, variant: Some(*variant) }
            }
            (Projection::Field(index), TyKind::Enum(id)) => {
                let Some(variant) = at.variant else { return plain(at.ty) };
                let fields = &self.types.enum_def(*id).variants[variant].fields;
                plain(fields.get(*index).map(|f| f.ty).unwrap_or(at.ty))
            }
            (Projection::Field(index), TyKind::Struct(id)) => {
                let fields = &self.types.struct_def(*id).fields;
                plain(fields.get(*index).map(|f| f.ty).unwrap_or(at.ty))
            }
            (Projection::Field(index), TyKind::Tuple(items)) => {
                plain(items.get(*index).copied().unwrap_or(at.ty))
            }
            (
                Projection::Index(_) | Projection::ConstIndex(_),
                TyKind::Array { elem, .. } | TyKind::Vec { elem },
            ) => plain(*elem),
            // `.len` and `.cap` on the runtime buffer are `usize`; `.ptr` is
            // never projected through, so it keeps the buffer's own type.
            (Projection::Field(index), TyKind::Vec { .. }) => {
                if *index == 0 { at } else { plain(self.usize_ty) }
            }
            (Projection::Deref, TyKind::Ref { inner, .. } | TyKind::Ptr { inner, .. }) => {
                plain(*inner)
            }
            _ => at,
        }
    }

    fn operand(&self, operand: &Operand, body: &Body) -> String {
        match operand {
            // A move and a copy generate the same C; the difference is a fact
            // the borrow checker uses, not a code shape.
            Operand::Copy(p) | Operand::Move(p) => self.place_in(p, body),
            Operand::Const(c) => self.constant(c),
        }
    }

    fn constant(&self, constant: &Const) -> String {
        match constant {
            Const::Int { value, ty } => {
                let suffix = match self.types.kind(*ty) {
                    TyKind::Int(IntTy::I64 | IntTy::Isize) => "LL",
                    TyKind::Uint(UintTy::U64 | UintTy::Usize) => "ULL",
                    TyKind::Uint(_) => "U",
                    _ => "",
                };
                format!("{value}{suffix}")
            }
            Const::Float { value, ty } => {
                let is_f32 = matches!(self.types.kind(*ty), TyKind::Float(FloatTy::F32));
                render_float(*value, is_f32)
            }
            Const::Bool(v) => if *v { "true" } else { "false" }.to_string(),
            Const::Str(text) => {
                format!("ember_str_lit({}, {})", c_string_literal(text), text.len())
            }
            Const::Void => "0".to_string(),
        }
    }

    /// `target` is the type of the place being assigned. A tuple or array
    /// aggregate needs it to name the generated struct it is building.
    fn rvalue(&self, rvalue: &Rvalue, body: &Body, target: Ty) -> String {
        match rvalue {
            Rvalue::Use(o) => self.operand(o, body),
            Rvalue::BinaryOp { op, lhs, rhs } => {
                format!(
                    "({} {} {})",
                    self.operand(lhs, body),
                    op.c_operator(),
                    self.operand(rhs, body)
                )
            }
            Rvalue::UnaryOp { op, operand } => {
                let operand = self.operand(operand, body);
                match op {
                    ember_mir::UnOp::Neg => format!("(-{operand})"),
                    ember_mir::UnOp::Not => format!("(!{operand})"),
                    ember_mir::UnOp::BitNot => format!("(~{operand})"),
                }
            }
            Rvalue::Cast { kind, operand, to } => {
                let value = self.operand(operand, body);
                let ty = self.c_type(*to);
                match kind {
                    // A widening is lossless by construction (`[TYP-5]`), so
                    // the C cast is exact.
                    CastKind::Widen | CastKind::Numeric => format!("(({ty}){value})"),
                }
            }
            Rvalue::Aggregate { kind, operands } => {
                let values: Vec<String> = operands.iter().map(|o| self.operand(o, body)).collect();
                if let AggregateKind::Enum(id, variant) = kind {
                    return self.enum_value(*id, *variant, &values);
                }
                let name = match kind {
                    AggregateKind::Struct(id) => {
                        format!("em_{}", self.types.struct_def(*id).name)
                    }
                    _ => self.c_type(target),
                };
                // An empty aggregate still has the padding member `[STR-4]`
                // gives it, and C wants an initialiser for it.
                if values.is_empty() {
                    return format!("({name}){{ 0 }}");
                }
                match kind {
                    // The array's elements sit inside the wrapper's one
                    // member, so they need their own brace level.
                    AggregateKind::Array => format!("({name}){{ {{ {} }} }}", values.join(", ")),
                    _ => format!("({name}){{ {} }}", values.join(", ")),
                }
            }
            // `[ENM-3]` — a unit-only enum is its tag, so reading the
            // discriminant is reading the value.
            Rvalue::Discriminant(place) => {
                let read = self.place_in(place, body);
                let ty = self.place_ty(place, body);
                match self.types.kind(ty) {
                    TyKind::Enum(id) if !self.types.enum_def(*id).is_unit_only() => {
                        format!("{read}.tag")
                    }
                    _ => read,
                }
            }
            Rvalue::Ref { place, .. } => format!("&{}", self.place_in(place, body)),
            // `[value; count]` is emitted as a loop by `emit_stmt`; it is
            // built only ever as the right-hand side of an assignment.
            Rvalue::Repeat { .. } => {
                unreachable!("Rvalue::Repeat is emitted by emit_stmt, not as an expression")
            }
        }
    }

    /// One enum value. A unit-only enum is just its discriminant; a payload
    /// enum sets the tag and the one union member that variant uses.
    /// Designated initialisers name both, so nothing is left uninitialised
    /// and `-Wmissing-field-initializers` has nothing to say.
    fn enum_value(&self, id: EnumId, variant: usize, values: &[String]) -> String {
        let def = self.types.enum_def(id);
        let name = format!("em_{}", def.name);
        let tag = def.variants[variant].discriminant;
        if def.is_unit_only() {
            return format!("(({name}){tag})");
        }
        if values.is_empty() {
            return format!("({name}){{ .tag = {tag} }}");
        }
        format!(
            "({name}){{ .tag = {tag}, .payload = {{ .{} = {{ {} }} }} }}",
            def.variants[variant].name,
            values.join(", ")
        )
    }

    // -- types ----------------------------------------------------------------

    fn is_void(&self, ty: ember_types::Ty) -> bool {
        matches!(self.types.kind(ty), TyKind::Void | TyKind::Never | TyKind::Error)
    }

    /// Part XVIII §6's type mapping table.
    fn c_type(&self, ty: ember_types::Ty) -> String {
        match self.types.kind(ty) {
            TyKind::Bool => "bool".into(),
            TyKind::Char => "uint32_t".into(),
            TyKind::Int(i) => match i {
                IntTy::I8 => "int8_t",
                IntTy::I16 => "int16_t",
                IntTy::I32 => "int32_t",
                IntTy::I64 => "int64_t",
                IntTy::I128 => "ember_i128",
                IntTy::Isize => "ptrdiff_t",
            }
            .into(),
            TyKind::Uint(u) => match u {
                UintTy::U8 => "uint8_t",
                UintTy::U16 => "uint16_t",
                UintTy::U32 => "uint32_t",
                UintTy::U64 => "uint64_t",
                UintTy::U128 => "ember_u128",
                UintTy::Usize => "size_t",
            }
            .into(),
            TyKind::Float(f) => match f {
                // `[TYP-9]` — f16 arithmetic is performed in f32 and rounded
                // on the C backend; the storage form is a bit pattern.
                FloatTy::F16 => "uint16_t",
                FloatTy::F32 => "float",
                FloatTy::F64 => "double",
            }
            .into(),
            TyKind::Void | TyKind::Never | TyKind::Error => "void".into(),
            TyKind::Str => "ember_str".into(),
            TyKind::Struct(id) => format!("em_{}", self.types.struct_def(*id).name),
            TyKind::Enum(id) => format!("em_{}", self.types.enum_def(*id).name),
            TyKind::Ref { mutable, inner } | TyKind::Ptr { mutable, inner } => {
                let inner = self.c_type(*inner);
                if *mutable { format!("{inner}*") } else { format!("const {inner}*") }
            }
            TyKind::Array { .. } | TyKind::Tuple(_) => self.structural_name(ty),
            // Every `Array[T]` and `String` is the same buffer; the element
            // size travels with each runtime call instead of with the type.
            TyKind::Vec { .. } => "ember_vec".into(),
            TyKind::Fn { .. } => "void*".into(),
            TyKind::Infer(_) | TyKind::IntLit | TyKind::FloatLit => "int32_t".into(),
        }
    }

    /// `[FN-8]` — the C entry point initialises the runtime, calls Ember's
    /// `main`, and shuts down. `[RT-2]`: there are no global constructors, so
    /// this is the only place initialisation can happen.
    fn emit_entry_point(&mut self) {
        self.line("int main(int argc, char** argv) {");
        self.line("    ember_rt_config cfg = ember_rt_config_default();");
        self.line("    (void)argc; (void)argv;");
        self.line("    ember_rt_init(&cfg);");
        self.line("    em_main();");
        self.line("    ember_rt_shutdown();");
        self.line("    return 0;");
        self.line("}");
    }
}

/// Work out what type definitions the module needs and in what order.
///
/// `[CG-C-2]` — the walk is over the interner and the struct table in their
/// own order, so the result is the same for the same input.
fn plan_types(types: &TypeTable) -> (Vec<TypeNode>, BTreeMap<Ty, String>) {
    let mut planner = Planner {
        types,
        order: Vec::new(),
        names: BTreeMap::new(),
        done: BTreeSet::new(),
        active: BTreeSet::new(),
        taken: types
            .structs()
            .map(|(_, d)| format!("em_{}", d.name))
            .chain(types.enums().map(|(_, d)| format!("em_{}", d.name)))
            .collect(),
    };
    // Named types first, so the output stays close to declaration order; each
    // pulls in whatever it contains.
    let structs: Vec<StructId> = types.structs().map(|(id, _)| id).collect();
    for id in structs {
        planner.visit(TypeNode::Struct(id));
    }
    let enums: Vec<EnumId> = types.enums().map(|(id, _)| id).collect();
    for id in enums {
        planner.visit(TypeNode::Enum(id));
    }
    let structural: Vec<Ty> = types
        .all()
        .filter(|(_, k)| matches!(k, TyKind::Tuple(_) | TyKind::Array { .. }))
        .map(|(ty, _)| ty)
        .collect();
    for ty in structural {
        planner.visit(TypeNode::Structural(ty));
    }
    (planner.order, planner.names)
}

struct Planner<'a> {
    types: &'a TypeTable,
    order: Vec<TypeNode>,
    names: BTreeMap<Ty, String>,
    done: BTreeSet<TypeNode>,
    active: BTreeSet<TypeNode>,
    taken: BTreeSet<String>,
}

impl Planner<'_> {
    fn visit(&mut self, node: TypeNode) {
        // `!insert` means the node is already on the stack, which is a type
        // that contains itself by value. `E2200` reports that; stopping here
        // keeps the backend from recursing forever on a program that is
        // already rejected.
        if self.done.contains(&node) || !self.active.insert(node) {
            return;
        }
        match node {
            TypeNode::Struct(id) => {
                let fields: Vec<Ty> =
                    self.types.struct_def(id).fields.iter().map(|f| f.ty).collect();
                for field in fields {
                    self.require(field);
                }
            }
            TypeNode::Enum(id) => {
                let payloads: Vec<Ty> = self
                    .types
                    .enum_def(id)
                    .variants
                    .iter()
                    .flat_map(|v| v.fields.iter().map(|f| f.ty))
                    .collect();
                for payload in payloads {
                    self.require(payload);
                }
            }
            TypeNode::Structural(ty) => {
                let contains: Vec<Ty> = match self.types.kind(ty) {
                    TyKind::Tuple(items) => items.clone(),
                    TyKind::Array { elem, .. } => vec![*elem],
                    _ => Vec::new(),
                };
                for inner in contains {
                    self.require(inner);
                }
                let name = self.fresh_name(ty);
                self.names.insert(ty, name);
            }
        }
        self.active.remove(&node);
        self.done.insert(node);
        self.order.push(node);
    }

    /// A type held by value needs its definition first. Behind a reference or
    /// a pointer it does not, because every definition is forward-declared.
    fn require(&mut self, ty: Ty) {
        match self.types.kind(ty) {
            TyKind::Struct(id) => self.visit(TypeNode::Struct(*id)),
            TyKind::Enum(id) => self.visit(TypeNode::Enum(*id)),
            TyKind::Tuple(_) | TyKind::Array { .. } => self.visit(TypeNode::Structural(ty)),
            _ => {}
        }
    }

    /// A readable name derived from how the type prints, made unique against
    /// every name already used. The suffix only ever appears when a user type
    /// happens to be named like a generated one.
    fn fresh_name(&mut self, ty: Ty) -> String {
        let stem = identifier_from(&self.types.display(ty));
        let prefix = match self.types.kind(ty) {
            TyKind::Tuple(_) => "em_tup_",
            _ => "em_arr_",
        };
        let base = format!("{prefix}{stem}");
        if self.taken.insert(base.clone()) {
            return base;
        }
        let mut n: u32 = 2;
        loop {
            let candidate = format!("{base}_{n}");
            if self.taken.insert(candidate.clone()) {
                return candidate;
            }
            n += 1;
        }
    }
}

/// Turn a printed type such as `(i32, f32)` or `[f32; 4]` into the readable
/// core of a C identifier: `i32_f32`, `f32_4`.
fn identifier_from(shown: &str) -> String {
    let mut out = String::new();
    for ch in shown.chars() {
        if ch.is_ascii_alphanumeric() {
            out.push(ch);
        } else if !out.ends_with('_') {
            out.push('_');
        }
    }
    out.trim_matches('_').to_string()
}

/// Locals and parameters that are never read anywhere in the body.
///
/// A method that ignores its receiver — `fn sides(self) -> i32: return 4` — is
/// ordinary Ember, and so is a `_`-shaped parameter, but both trip
/// `-Wunused-parameter`.
fn unread_locals(body: &Body) -> Vec<usize> {
    let mut read = vec![false; body.locals.len()];

    fn read_place(place: &Place, read: &mut [bool]) {
        read[place.local.0 as usize] = true;
        for projection in &place.projection {
            if let Projection::Index(local) = projection {
                read[local.0 as usize] = true;
            }
        }
    }
    fn read_operand(operand: &Operand, read: &mut [bool]) {
        match operand {
            Operand::Copy(place) | Operand::Move(place) => read_place(place, read),
            Operand::Const(_) => {}
        }
    }
    // A projection on the left of an assignment reads the local it starts
    // from: `x.f = 1` needs `x`.
    fn write_place(place: &Place, read: &mut [bool]) {
        if !place.projection.is_empty() {
            read_place(place, read);
        }
    }

    for block in &body.blocks {
        for stmt in &block.stmts {
            match &stmt.kind {
                StmtKind::Assign { place, rvalue } => {
                    write_place(place, &mut read);
                    match rvalue {
                        Rvalue::Use(o) | Rvalue::UnaryOp { operand: o, .. } => {
                            read_operand(o, &mut read)
                        }
                        Rvalue::Cast { operand, .. } => read_operand(operand, &mut read),
                        Rvalue::BinaryOp { lhs, rhs, .. } => {
                            read_operand(lhs, &mut read);
                            read_operand(rhs, &mut read);
                        }
                        Rvalue::Aggregate { operands, .. } => {
                            operands.iter().for_each(|o| read_operand(o, &mut read))
                        }
                        Rvalue::Repeat { value, .. } => read_operand(value, &mut read),
                        Rvalue::Discriminant(place) => read_place(place, &mut read),
                        // Taking a local's address counts as using it: the
                        // callee may write through the reference.
                        Rvalue::Ref { place, .. } => {
                            read[place.local.0 as usize] = true;
                            read_place(place, &mut read);
                        }
                    }
                }
                StmtKind::CheckedBinaryOp { dest, overflow, lhs, rhs, .. } => {
                    write_place(dest, &mut read);
                    write_place(overflow, &mut read);
                    read_operand(lhs, &mut read);
                    read_operand(rhs, &mut read);
                }
                StmtKind::StorageLive(_) | StmtKind::StorageDead(_) | StmtKind::Nop => {}
            }
        }
        match &block.terminator {
            Terminator::SwitchInt { discr, .. } => read_operand(discr, &mut read),
            Terminator::Call { args, dest, .. } => {
                args.iter().for_each(|a| read_operand(a, &mut read));
                write_place(dest, &mut read);
            }
            Terminator::Assert { cond, msg, .. } => {
                read_operand(cond, &mut read);
                if let AssertKind::Bounds { len, index } = msg {
                    read_operand(len, &mut read);
                    read_operand(index, &mut read);
                }
            }
            Terminator::Return => read[RETURN_LOCAL.0 as usize] = true,
            Terminator::Goto(_) | Terminator::Unreachable => {}
        }
    }

    body.locals
        .iter()
        .enumerate()
        .filter(|(index, decl)| decl.kind != LocalKind::Return && !read[*index])
        .map(|(index, _)| index)
        .collect()
}

/// Which blocks are the target of a `goto` in the emitted C.
///
/// This must agree exactly with `emit_terminator`'s fallthrough rule: a jump
/// to the next block in order emits no `goto`, so it does not make that block
/// referenced.
fn referenced_blocks(body: &Body) -> std::collections::BTreeSet<usize> {
    let mut referenced = std::collections::BTreeSet::new();
    for (index, block) in body.blocks.iter().enumerate() {
        match &block.terminator {
            Terminator::Goto(target)
            | Terminator::Call { next: target, .. }
            | Terminator::Assert { next: target, .. } => {
                if target.0 as usize != index + 1 {
                    referenced.insert(target.0 as usize);
                }
            }
            Terminator::SwitchInt { targets, otherwise, .. } => {
                for (_, target) in targets {
                    referenced.insert(target.0 as usize);
                }
                referenced.insert(otherwise.0 as usize);
            }
            Terminator::Return | Terminator::Unreachable => {}
        }
    }
    referenced
}

/// The `ember_ck_*` stem for an operator.
fn checked_name(op: ember_mir::BinOp) -> &'static str {
    use ember_mir::BinOp;
    match op {
        BinOp::Add => "add",
        BinOp::Sub => "sub",
        BinOp::Mul => "mul",
        BinOp::Div => "div",
        BinOp::Rem => "rem",
        // Nothing else is lowered through `CheckedBinaryOp`.
        _ => "add",
    }
}

/// Render a float so that the C compiler reads back exactly the value Ember
/// computed. Shortest round-tripping decimal, then the `f` suffix for `f32`.
fn render_float(value: f64, is_f32: bool) -> String {
    if value.is_nan() {
        return if is_f32 { "EMBER_NAN_F32".into() } else { "EMBER_NAN_F64".into() };
    }
    if value.is_infinite() {
        let sign = if value < 0.0 { "-" } else { "" };
        return format!("{sign}EMBER_INF_F64");
    }
    for precision in 1..=17 {
        let text = format!("{value:.*e}", precision);
        if text.parse::<f64>() == Ok(value) {
            let rendered = format!("{value:.*e}", precision);
            return if is_f32 { format!("(float){rendered}") } else { rendered };
        }
    }
    let text = format!("{value:e}");
    if is_f32 { format!("(float){text}") } else { text }
}

/// A C string literal with every byte escaped that needs it. Non-ASCII bytes
/// are emitted as hex escapes so the file stays ASCII whatever the compiler's
/// source charset is.
fn c_string_literal(text: &str) -> String {
    let mut out = String::from("\"");
    for byte in text.bytes() {
        match byte {
            b'"' => out.push_str("\\\""),
            b'\\' => out.push_str("\\\\"),
            b'\n' => out.push_str("\\n"),
            b'\r' => out.push_str("\\r"),
            b'\t' => out.push_str("\\t"),
            0x20..=0x7E => out.push(byte as char),
            // `\xNN` followed by a hex digit would keep consuming, so close
            // and reopen the literal.
            other => out.push_str(&format!("\\x{other:02x}\" \"")),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn floats_round_trip_through_the_emitted_text() {
        for value in [0.1f64, 1.0, 5.0, 1e300, -2.5, 1.0 / 3.0] {
            let text = render_float(value, false);
            assert_eq!(text.parse::<f64>(), Ok(value), "{value} rendered as {text}");
        }
    }

    #[test]
    fn f32_constants_are_cast_so_the_c_compiler_does_not_widen() {
        let text = render_float(0.5, true);
        assert!(text.starts_with("(float)"), "{text}");
    }

    #[test]
    fn string_literals_escape_what_c_needs() {
        assert_eq!(c_string_literal("a\"b\\c\n"), "\"a\\\"b\\\\c\\n\"");
    }

    #[test]
    fn non_ascii_bytes_do_not_swallow_the_next_character() {
        // "\xc3\xa9" followed by 'a' must not lex as "\xc3a9a".
        let text = c_string_literal("éa");
        assert!(text.contains("\\xc3\" \""), "{text}");
        assert!(text.ends_with("a\""), "{text}");
    }
}
