//! The C11 backend: MIR to C (Part XVIII §6).
//!
//! `[CG-C-1]` — the emitted C must compile warning-free under
//! `-std=c11 -Wall -Wextra` and `/W3`, be free of undefined behaviour by
//! construction, and depend on no compiler extension except through
//! `ember_rt.h` macros that have portable fallbacks.
//!
//! `[CG-C-2]` — the output is deterministic for identical input: ordering is
//! stable and nothing is keyed on a pointer, so the build cache and
//! `diff`-based review both work.

use std::fmt::Write as _;

use ember_mir::{
    AggregateKind, Builtin, Body, CastKind, Const, FuncRef, LocalKind, Operand, Place, Projection, Rvalue,
    Stmt, Terminator,
};
use ember_span::SourceMap;
use ember_types::{FloatTy, IntTy, TyKind, TypeTable, UintTy};

pub struct Output {
    /// The single translation unit for this module.
    pub c_source: String,
}

pub fn emit(
    bodies: &[Body],
    types: &TypeTable,
    map: &SourceMap,
    module_name: &str,
    has_main: bool,
) -> Output {
    let mut emitter = Emitter { types, map, out: String::new(), line_directives: true };
    emitter.emit_module(bodies, module_name, has_main);
    Output { c_source: emitter.out }
}

struct Emitter<'a> {
    types: &'a TypeTable,
    map: &'a SourceMap,
    out: String,
    line_directives: bool,
}

impl Emitter<'_> {
    fn line(&mut self, text: &str) {
        self.out.push_str(text);
        self.out.push('\n');
    }

    fn emit_module(&mut self, bodies: &[Body], module_name: &str, has_main: bool) {
        self.line("/* Generated by the Ember compiler. Do not edit. */");
        self.line(&format!("/* module: {module_name} */"));
        self.line("");
        self.line("#include \"ember_rt.h\"");
        self.line("");

        self.emit_type_declarations();
        self.emit_prototypes(bodies);

        for body in bodies {
            self.emit_body(body);
        }

        if has_main {
            self.emit_entry_point();
        }
    }

    /// `ember_types.h`'s content, inlined into the single translation unit
    /// Phase 0 emits. Structs are declared in the order they were interned,
    /// which is declaration order, so a struct's fields are always already
    /// complete types.
    fn emit_type_declarations(&mut self) {
        let structs: Vec<(String, Vec<(String, String)>)> = self
            .types
            .structs()
            .map(|(_, def)| {
                let fields = def
                    .fields
                    .iter()
                    .map(|f| (self.c_type(f.ty), f.name.to_string()))
                    .collect();
                (def.name.to_string(), fields)
            })
            .collect();

        if structs.is_empty() {
            return;
        }
        self.line("/* types */");
        for (name, _) in &structs {
            self.line(&format!("typedef struct em_{name} em_{name};"));
        }
        for (name, fields) in &structs {
            self.line(&format!("struct em_{name} {{"));
            if fields.is_empty() {
                // `[STR-4]` — a zero-sized struct is legal in Ember but not in
                // C, so it gets a padding byte. Its size is never observed
                // through the C type.
                self.line("    char _empty;");
            }
            for (ty, field) in fields {
                self.line(&format!("    {ty} {field};"));
            }
            self.line("};");
        }
        self.line("");
    }

    fn emit_prototypes(&mut self, bodies: &[Body]) {
        if bodies.is_empty() {
            return;
        }
        self.line("/* prototypes */");
        for body in bodies {
            let signature = self.signature(body);
            self.line(&format!("static {signature};"));
        }
        self.line("");
    }

    fn signature(&self, body: &Body) -> String {
        let ret = self.c_type(body.return_ty());
        let params: Vec<String> = body
            .args()
            .map(|(id, decl)| format!("{} _{}", self.c_type(decl.ty), id.0))
            .collect();
        let params = if params.is_empty() { "void".to_string() } else { params.join(", ") };
        format!("{ret} {}({params})", body.symbol)
    }

    fn emit_body(&mut self, body: &Body) {
        let signature = self.signature(body);
        self.line(&format!("static {signature} {{"));

        // Locals. Parameters are already C parameters; the return slot and
        // every other local are declared here.
        for (index, decl) in body.locals.iter().enumerate() {
            if decl.kind == LocalKind::Arg {
                continue;
            }
            if self.is_void(decl.ty) {
                continue;
            }
            let comment = match &decl.name {
                Some(name) => format!("  /* {name} */"),
                None => String::new(),
            };
            self.line(&format!("    {} _{index};{comment}", self.c_type(decl.ty)));
        }
        if body.locals.iter().any(|d| d.kind != LocalKind::Arg && !self.is_void(d.ty)) {
            self.line("");
        }

        // Only blocks something actually jumps to get a label: an unreferenced
        // label is a warning under `-Wall` and MSVC's C4102, and `[CG-C-1]`
        // requires the emitted C to compile without warnings.
        let referenced = referenced_blocks(body);
        for (index, block) in body.blocks.iter().enumerate() {
            if referenced.contains(&index) {
                // A label with no statement after it is a syntax error in C,
                // so every label is followed by at least `;`.
                self.line(&format!("bb{index}: ;"));
            }
            for stmt in &block.stmts {
                self.emit_stmt(stmt, body);
            }
            self.emit_terminator(&block.terminator, body, index);
        }

        self.line("}");
        self.line("");
    }

    fn emit_stmt(&mut self, stmt: &Stmt, body: &Body) {
        match stmt {
            Stmt::Assign { place, rvalue } => {
                let ty = self.place_ty(place, body);
                if self.is_void(ty) {
                    return;
                }
                self.emit_line_directive(body, place);
                let lhs = self.place_in(place, body);
                let rhs = self.rvalue(rvalue, body);
                self.line(&format!("    {lhs} = {rhs};"));
            }
            // Storage markers carry no code in C; the borrow checker and drop
            // elaboration consume them before this point.
            Stmt::StorageLive(_) | Stmt::StorageDead(_) | Stmt::Nop => {}
        }
    }

    /// `#line` maps every emitted statement back to its Ember source
    /// (Part XVIII §6, "Debug info").
    fn emit_line_directive(&mut self, body: &Body, place: &Place) {
        if !self.line_directives {
            return;
        }
        let span = body.local(place.local).span;
        if span.is_dummy() || self.map.get(span.file).is_none() {
            return;
        }
        let file = self.map.file(span.file);
        let line = file.line_of(span.start);
        // Forward slashes: a backslash in a `#line` path is an escape.
        let path = file.path.display().to_string().replace('\\', "/");
        let _ = writeln!(self.out, "#line {line} \"{path}\"");
    }

    fn emit_terminator(&mut self, terminator: &Terminator, body: &Body, index: usize) {
        match terminator {
            Terminator::Goto(target) => {
                // A jump to the next block in order is a fallthrough.
                if target.0 as usize == index + 1 {
                    self.line("    /* fallthrough */");
                } else {
                    self.line(&format!("    goto bb{};", target.0));
                }
            }
            Terminator::SwitchInt { discr, targets, otherwise } => {
                let discr = self.operand(discr, body);
                // Phase 0 only produces two-way branches on a boolean.
                if let [(value, target)] = targets.as_slice() {
                    self.line(&format!(
                        "    if ({discr} == {value}) {{ goto bb{}; }} else {{ goto bb{}; }}",
                        target.0, otherwise.0
                    ));
                } else {
                    self.line(&format!("    switch ({discr}) {{"));
                    for (value, target) in targets {
                        self.line(&format!("    case {value}: goto bb{};", target.0));
                    }
                    self.line(&format!("    default: goto bb{};", otherwise.0));
                    self.line("    }");
                }
            }
            Terminator::Return => {
                if self.is_void(body.return_ty()) {
                    self.line("    return;");
                } else {
                    self.line("    return _0;");
                }
            }
            Terminator::Unreachable => {
                self.line("    EMBER_UNREACHABLE();");
            }
            Terminator::Call { func, args, dest, next } => {
                let call = self.call_expression(func, args, body);
                let dest_ty = self.place_ty(dest, body);
                if self.is_void(dest_ty) {
                    self.line(&format!("    {call};"));
                } else {
                    let dest_text = self.place_in(dest, body);
                    self.line(&format!("    {dest_text} = {call};"));
                }
                if next.0 as usize == index + 1 {
                    self.line("    /* fallthrough */");
                } else {
                    self.line(&format!("    goto bb{};", next.0));
                }
            }
        }
    }

    fn call_expression(&self, func: &FuncRef, args: &[Operand], body: &Body) -> String {
        let rendered: Vec<String> = args.iter().map(|a| self.operand(a, body)).collect();
        match func {
            FuncRef::Direct { symbol } => format!("{symbol}({})", rendered.join(", ")),
            FuncRef::Builtin { which, arg_ty } => {
                let suffix = self.builtin_suffix(*arg_ty);
                let name = match which {
                    Builtin::Println => "ember_println",
                    Builtin::Print => "ember_print",
                };
                format!("{name}_{suffix}({})", rendered.join(", "))
            }
        }
    }

    /// Which `ember_rt` printer a builtin call resolves to. Phase 0 has no
    /// `Display` interface, so the choice is made here from the argument type.
    fn builtin_suffix(&self, ty: ember_types::Ty) -> &'static str {
        match self.types.kind(ty) {
            TyKind::Bool => "bool",
            TyKind::Char => "char",
            TyKind::Int(_) => "i64",
            TyKind::Uint(_) => "u64",
            TyKind::Float(FloatTy::F64) => "f64",
            TyKind::Float(_) => "f32",
            TyKind::Str => "str",
            _ => "str",
        }
    }

    // -- places, operands, rvalues -------------------------------------------

    fn place_in(&self, place: &Place, body: &Body) -> String {
        let mut out = format!("_{}", place.local.0);
        let mut ty = body.local(place.local).ty;
        for projection in &place.projection {
            match projection {
                Projection::Field(index) => {
                    let TyKind::Struct(id) = *self.types.kind(ty) else {
                        out.push_str(&format!(".f{index}"));
                        continue;
                    };
                    let def = self.types.struct_def(id);
                    out.push_str(&format!(".{}", def.fields[*index].name));
                    ty = def.fields[*index].ty;
                }
                Projection::Index(local) => out.push_str(&format!("[_{}]", local.0)),
                Projection::ConstIndex(i) => out.push_str(&format!("[{i}]")),
                Projection::Deref => out = format!("(*{out})"),
                Projection::Column(i) => out.push_str(&format!(".col{i}")),
            }
        }
        out
    }

    fn place_ty(&self, place: &Place, body: &Body) -> ember_types::Ty {
        let mut ty = body.local(place.local).ty;
        for projection in &place.projection {
            if let Projection::Field(index) = projection {
                if let TyKind::Struct(id) = *self.types.kind(ty) {
                    ty = self.types.struct_def(id).fields[*index].ty;
                }
            }
        }
        ty
    }

    fn operand(&self, operand: &Operand, body: &Body) -> String {
        match operand {
            // A move and a copy generate the same C; the difference is a fact
            // the borrow checker uses, not a code shape.
            Operand::Copy(p) | Operand::Move(p) => self.place_in(p, body),
            Operand::Const(c) => self.constant(c),
        }
    }

    fn constant(&self, constant: &Const) -> String {
        match constant {
            Const::Int { value, ty } => {
                let suffix = match self.types.kind(*ty) {
                    TyKind::Int(IntTy::I64 | IntTy::Isize) => "LL",
                    TyKind::Uint(UintTy::U64 | UintTy::Usize) => "ULL",
                    TyKind::Uint(_) => "U",
                    _ => "",
                };
                format!("{value}{suffix}")
            }
            Const::Float { value, ty } => {
                let is_f32 = matches!(self.types.kind(*ty), TyKind::Float(FloatTy::F32));
                render_float(*value, is_f32)
            }
            Const::Bool(v) => if *v { "true" } else { "false" }.to_string(),
            Const::Str(text) => {
                format!("ember_str_lit({}, {})", c_string_literal(text), text.len())
            }
            Const::Void => "0".to_string(),
        }
    }

    fn rvalue(&self, rvalue: &Rvalue, body: &Body) -> String {
        match rvalue {
            Rvalue::Use(o) => self.operand(o, body),
            Rvalue::BinaryOp { op, lhs, rhs } => {
                format!(
                    "({} {} {})",
                    self.operand(lhs, body),
                    op.c_operator(),
                    self.operand(rhs, body)
                )
            }
            Rvalue::UnaryOp { op, operand } => {
                let operand = self.operand(operand, body);
                match op {
                    ember_mir::UnOp::Neg => format!("(-{operand})"),
                    ember_mir::UnOp::Not => format!("(!{operand})"),
                    ember_mir::UnOp::BitNot => format!("(~{operand})"),
                }
            }
            Rvalue::Cast { kind, operand, to } => {
                let value = self.operand(operand, body);
                let ty = self.c_type(*to);
                match kind {
                    // A widening is lossless by construction (`[TYP-5]`), so
                    // the C cast is exact.
                    CastKind::Widen | CastKind::Numeric => format!("(({ty}){value})"),
                }
            }
            Rvalue::Aggregate { kind, operands } => {
                let values: Vec<String> = operands.iter().map(|o| self.operand(o, body)).collect();
                match kind {
                    AggregateKind::Struct(id) => {
                        let name = self.types.struct_def(*id).name;
                        if values.is_empty() {
                            format!("(em_{name}){{ 0 }}")
                        } else {
                            format!("(em_{name}){{ {} }}", values.join(", "))
                        }
                    }
                    AggregateKind::Tuple => format!("{{ {} }}", values.join(", ")),
                }
            }
        }
    }

    // -- types ----------------------------------------------------------------

    fn is_void(&self, ty: ember_types::Ty) -> bool {
        matches!(self.types.kind(ty), TyKind::Void | TyKind::Never | TyKind::Error)
    }

    /// Part XVIII §6's type mapping table.
    fn c_type(&self, ty: ember_types::Ty) -> String {
        match self.types.kind(ty) {
            TyKind::Bool => "bool".into(),
            TyKind::Char => "uint32_t".into(),
            TyKind::Int(i) => match i {
                IntTy::I8 => "int8_t",
                IntTy::I16 => "int16_t",
                IntTy::I32 => "int32_t",
                IntTy::I64 => "int64_t",
                IntTy::I128 => "ember_i128",
                IntTy::Isize => "ptrdiff_t",
            }
            .into(),
            TyKind::Uint(u) => match u {
                UintTy::U8 => "uint8_t",
                UintTy::U16 => "uint16_t",
                UintTy::U32 => "uint32_t",
                UintTy::U64 => "uint64_t",
                UintTy::U128 => "ember_u128",
                UintTy::Usize => "size_t",
            }
            .into(),
            TyKind::Float(f) => match f {
                // `[TYP-9]` — f16 arithmetic is performed in f32 and rounded
                // on the C backend; the storage form is a bit pattern.
                FloatTy::F16 => "uint16_t",
                FloatTy::F32 => "float",
                FloatTy::F64 => "double",
            }
            .into(),
            TyKind::Void | TyKind::Never | TyKind::Error => "void".into(),
            TyKind::Str => "ember_str".into(),
            TyKind::Struct(id) => format!("em_{}", self.types.struct_def(*id).name),
            TyKind::Ref { mutable, inner } | TyKind::Ptr { mutable, inner } => {
                let inner = self.c_type(*inner);
                if *mutable { format!("{inner}*") } else { format!("const {inner}*") }
            }
            TyKind::Array { elem, .. } => format!("{}*", self.c_type(*elem)),
            TyKind::Tuple(_) | TyKind::Fn { .. } => "void*".into(),
            TyKind::Infer(_) | TyKind::IntLit | TyKind::FloatLit => "int32_t".into(),
        }
    }

    /// `[FN-8]` — the C entry point initialises the runtime, calls Ember's
    /// `main`, and shuts down. `[RT-2]`: there are no global constructors, so
    /// this is the only place initialisation can happen.
    fn emit_entry_point(&mut self) {
        self.line("int main(int argc, char** argv) {");
        self.line("    ember_rt_config cfg = ember_rt_config_default();");
        self.line("    (void)argc; (void)argv;");
        self.line("    ember_rt_init(&cfg);");
        self.line("    em_main();");
        self.line("    ember_rt_shutdown();");
        self.line("    return 0;");
        self.line("}");
    }
}

/// Which blocks are the target of a `goto` in the emitted C.
///
/// This must agree exactly with `emit_terminator`'s fallthrough rule: a jump
/// to the next block in order emits no `goto`, so it does not make that block
/// referenced.
fn referenced_blocks(body: &Body) -> std::collections::BTreeSet<usize> {
    let mut referenced = std::collections::BTreeSet::new();
    for (index, block) in body.blocks.iter().enumerate() {
        match &block.terminator {
            Terminator::Goto(target) | Terminator::Call { next: target, .. } => {
                if target.0 as usize != index + 1 {
                    referenced.insert(target.0 as usize);
                }
            }
            Terminator::SwitchInt { targets, otherwise, .. } => {
                for (_, target) in targets {
                    referenced.insert(target.0 as usize);
                }
                referenced.insert(otherwise.0 as usize);
            }
            Terminator::Return | Terminator::Unreachable => {}
        }
    }
    referenced
}

/// Render a float so that the C compiler reads back exactly the value Ember
/// computed. Shortest round-tripping decimal, then the `f` suffix for `f32`.
fn render_float(value: f64, is_f32: bool) -> String {
    if value.is_nan() {
        return if is_f32 { "EMBER_NAN_F32".into() } else { "EMBER_NAN_F64".into() };
    }
    if value.is_infinite() {
        let sign = if value < 0.0 { "-" } else { "" };
        return format!("{sign}EMBER_INF_F64");
    }
    for precision in 1..=17 {
        let text = format!("{value:.*e}", precision);
        if text.parse::<f64>() == Ok(value) {
            let rendered = format!("{value:.*e}", precision);
            return if is_f32 { format!("(float){rendered}") } else { rendered };
        }
    }
    let text = format!("{value:e}");
    if is_f32 { format!("(float){text}") } else { text }
}

/// A C string literal with every byte escaped that needs it. Non-ASCII bytes
/// are emitted as hex escapes so the file stays ASCII whatever the compiler's
/// source charset is.
fn c_string_literal(text: &str) -> String {
    let mut out = String::from("\"");
    for byte in text.bytes() {
        match byte {
            b'"' => out.push_str("\\\""),
            b'\\' => out.push_str("\\\\"),
            b'\n' => out.push_str("\\n"),
            b'\r' => out.push_str("\\r"),
            b'\t' => out.push_str("\\t"),
            0x20..=0x7E => out.push(byte as char),
            // `\xNN` followed by a hex digit would keep consuming, so close
            // and reopen the literal.
            other => out.push_str(&format!("\\x{other:02x}\" \"")),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn floats_round_trip_through_the_emitted_text() {
        for value in [0.1f64, 1.0, 5.0, 1e300, -2.5, 1.0 / 3.0] {
            let text = render_float(value, false);
            assert_eq!(text.parse::<f64>(), Ok(value), "{value} rendered as {text}");
        }
    }

    #[test]
    fn f32_constants_are_cast_so_the_c_compiler_does_not_widen() {
        let text = render_float(0.5, true);
        assert!(text.starts_with("(float)"), "{text}");
    }

    #[test]
    fn string_literals_escape_what_c_needs() {
        assert_eq!(c_string_literal("a\"b\\c\n"), "\"a\\\"b\\\\c\\n\"");
    }

    #[test]
    fn non_ascii_bytes_do_not_swallow_the_next_character() {
        // "\xc3\xa9" followed by 'a' must not lex as "\xc3a9a".
        let text = c_string_literal("éa");
        assert!(text.contains("\\xc3\" \""), "{text}");
        assert!(text.ends_with("a\""), "{text}");
    }
}
