"""Generate the C runtime interface and implementation from one template.

The runtime is an output of the build, not a second place where the project's
symbol prefix is authored.  The source prefix is read from the canonical
``ember_branding`` macro, and the templates contain the current default names
only as replaceable tokens.  This keeps the generated C readable while making
the ``[RT-5]`` single-source rule mechanically checkable.

Usage::

    python tools/generate_runtime.py
    python tools/generate_runtime.py --check

``--out-dir`` and ``--prefix`` are useful for generator tests and for a future
packaging step; normal builds use the branding source and the checked-in
runtime directory.

The runtime's own C tests (``templates/tests/*.c.in``) call runtime functions
by name, so they are templates too, rendered into ``tests/`` beside ``src/``.
"""

from __future__ import annotations

import argparse
import difflib
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
BRANDING = ROOT / "compiler" / "ember_branding" / "src" / "lib.rs"
TEMPLATES = ROOT / "runtime" / "ember_rt" / "templates"
DEFAULT_OUT = ROOT / "runtime" / "ember_rt"
GENERATED_MARKER = "Generated by tools/generate_runtime.py; do not edit."
IDENTIFIER = re.compile(r"^[a-z][a-z0-9_]*$")


def branding_prefix() -> str:
    """Read the one source-of-truth prefix from the branding macro."""

    text = BRANDING.read_text(encoding="utf-8")
    match = re.search(
        r"macro_rules!\s*symbol_prefix\b.*?=>\s*\{\s*\"([A-Za-z_][A-Za-z0-9_]*)\"",
        text,
        re.DOTALL,
    )
    if match is None:
        raise RuntimeError(f"could not find symbol_prefix! in {BRANDING}")
    prefix = match.group(1)
    if not IDENTIFIER.fullmatch(prefix):
        raise RuntimeError(f"branding prefix is not a lower-case C identifier: {prefix!r}")
    return prefix


def render(template: str, prefix: str) -> str:
    """Substitute the lower/upper C spellings used by the runtime templates."""

    if not IDENTIFIER.fullmatch(prefix):
        raise ValueError(f"runtime prefix is not a lower-case C identifier: {prefix!r}")
    upper = prefix.upper()
    rendered = template.replace("EMBER_", f"{upper}_")
    rendered = rendered.replace("ember_", f"{prefix}_")
    # The macro's value is the only un-suffixed use that reaches C.
    rendered = re.sub(r"\bember\b", prefix, rendered)
    return f"/* {GENERATED_MARKER} */\n{rendered}"


def output_paths(out_dir: Path, prefix: str) -> tuple[Path, Path]:
    return (
        out_dir / "include" / f"{prefix}_rt.h",
        out_dir / "src" / f"{prefix}_rt.c",
    )


def generated_contents(prefix: str) -> tuple[str, str]:
    header = (TEMPLATES / "ember_rt.h.in").read_text(encoding="utf-8")
    source = (TEMPLATES / "ember_rt.c.in").read_text(encoding="utf-8")
    return render(header, prefix), render(source, prefix)


def generated_tests(out_dir: Path, prefix: str) -> list[tuple[Path, str]]:
    """Each C test template's output path and rendered text."""

    return [
        (out_dir / "tests" / template.name[: -len(".in")], render(template.read_text(encoding="utf-8"), prefix))
        for template in sorted((TEMPLATES / "tests").glob("*.c.in"))
    ]


def write_outputs(out_dir: Path, prefix: str) -> tuple[Path, Path]:
    header_path, source_path = output_paths(out_dir, prefix)
    header, source = generated_contents(prefix)
    header_path.parent.mkdir(parents=True, exist_ok=True)
    source_path.parent.mkdir(parents=True, exist_ok=True)
    header_path.write_text(header, encoding="utf-8", newline="\n")
    source_path.write_text(source, encoding="utf-8", newline="\n")
    for test_path, test in generated_tests(out_dir, prefix):
        test_path.parent.mkdir(parents=True, exist_ok=True)
        test_path.write_text(test, encoding="utf-8", newline="\n")
    return header_path, source_path


def check_outputs(out_dir: Path, prefix: str) -> bool:
    tests = generated_tests(out_dir, prefix)
    expected = [*generated_contents(prefix), *(test for _, test in tests)]
    paths = [*output_paths(out_dir, prefix), *(path for path, _ in tests)]
    ok = True
    for path, wanted in zip(paths, expected):
        if not path.exists():
            print(f"missing generated runtime output: {path}")
            ok = False
            continue
        actual = path.read_text(encoding="utf-8")
        if actual == wanted:
            continue
        print(f"generated runtime output is stale: {path}")
        print(
            "".join(
                difflib.unified_diff(
                    actual.splitlines(keepends=True),
                    wanted.splitlines(keepends=True),
                    fromfile=str(path),
                    tofile=f"{path} (generated)",
                )
            )
        )
        ok = False
    return ok


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify outputs without writing")
    parser.add_argument("--prefix", help="override the branding prefix (for generator tests)")
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=DEFAULT_OUT,
        help="runtime output root containing include/ and src/",
    )
    args = parser.parse_args()
    prefix = args.prefix or branding_prefix()
    if args.check:
        return 0 if check_outputs(args.out_dir, prefix) else 1
    paths = write_outputs(args.out_dir, prefix)
    print(f"generated {paths[0]} and {paths[1]} from {TEMPLATES}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
