"""Split the single-file Ember specification into one file per Part.

docs/spec/ is the canonical location of the specification (repo layout, XX.5).
Re-run after editing the source document; the split is generated, not edited.
"""
import re
import sys
from pathlib import Path

ROMAN = {
    "0": 0, "I": 1, "II": 2, "III": 3, "IV": 4, "V": 5, "VI": 6, "VII": 7,
    "VIII": 8, "IX": 9, "X": 10, "XI": 11, "XII": 12, "XIII": 13, "XIV": 14,
    "XV": 15, "XVI": 16, "XVII": 17, "XVIII": 18, "XIX": 19, "XX": 20,
    "XXI": 21, "XXII": 22, "XXIII": 23, "XXIV": 24, "XXV": 25,
}
HEADING = re.compile(r"^# (Part ([0-9IVX]+)|Appendix ([A-Z]))\b")


def slug(text):
    text = text.lower()
    text = re.sub(r"[^a-z0-9]+", "-", text)
    return text.strip("-")[:60]


def main(source, out_dir):
    lines = Path(source).read_text(encoding="utf-8").splitlines(keepends=True)
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    cuts = []  # (line index, filename stem, title)
    for i, line in enumerate(lines):
        m = HEADING.match(line)
        if not m:
            continue
        title = line[2:].strip()
        if m.group(2) is not None:
            n = ROMAN[m.group(2)]
            stem = f"part-{n:02d}-{slug(title.split('—')[-1])}"
        else:
            stem = f"appendix-{m.group(3).lower()}-{slug(title.split('—')[-1])}"
        cuts.append((i, stem, title))

    if not cuts:
        sys.exit("no Part headings found in " + source)

    written = []
    front = "".join(lines[: cuts[0][0]])
    (out_dir / "part-00-preface.md").write_text(front, encoding="utf-8")
    written.append(("part-00-preface.md", "Preface — how to use this document"))

    for idx, (start, stem, title) in enumerate(cuts):
        end = cuts[idx + 1][0] if idx + 1 < len(cuts) else len(lines)
        name = stem + ".md"
        (out_dir / name).write_text("".join(lines[start:end]), encoding="utf-8")
        written.append((name, title))

    index = ["# Ember specification (v0.2), by part\n",
             "\nGenerated by `tools/split_spec.py`. Edit the parts, not a combined copy.\n",
             "\n| File | Part |\n|---|---|\n"]
    for name, title in written:
        index.append(f"| [{name}]({name}) | {title} |\n")
    (out_dir / "README.md").write_text("".join(index), encoding="utf-8")

    print(f"wrote {len(written)} files to {out_dir}")
    for name, title in written:
        print(f"  {name}")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
