"""Appendix G data: every finding F-001..F-214 -> how 0.9.9 (Hardened_1, as amended by Hardened_2) resolves it.

kind:  SPEC    the language text changed or gained a rule
       IMPL    the rule stands (or was clarified); the compiler/runtime/std is wrong -> a defect to fix
       GATE    a test/CI gate or tool obligation now in the text
       OUT     outside the specification (process/docs/repo hygiene); the reason is given
       WDN     withdrawn
Each entry: (kind, resolution, [rule ids that carry it]).
"""

M = {
'F-001': ('OUT', 'Audit bookkeeping, not language text; `FINDINGS.md` Part D rebuilt the missing index.', []),
'F-002': ('IMPL', '`()` is the value of `void`; `Ok(())` is the success value of `Result[void, E]`.', ['TYP-27']),
'F-003': ('IMPL', '`import a.b.c` binds `c`; unknown modules are `E1060`.', ['MOD-3']),
'F-004': ('SPEC', 'An import of a missing module is `E1060`; nothing is accepted silently.', ['MOD-3', 'PHIL-12']),
'F-005': ('SPEC', 'The numeric-conversion note appears only when both operands are numeric.', ['TYP-4']),
'F-006': ('SPEC', 'Suggestion threshold scales with name length and kind.', ['DIA-24']),
'F-007': ('SPEC', 'A string literal initialises a `String` where one is expected.', ['TXT-9']),
'F-008': ('SPEC', 'A run of invalid characters is one diagnostic.', ['DIA-20']),
'F-009': ('SPEC', 'Unimplemented constructs are `E0900`, never a name-resolution code.', ['PHIL-12', 'CLI-19']),
'F-010': ('SPEC', 'Names bound to a failed import produce no further errors.', ['DIA-14']),
'F-011': ('SPEC', 'One error per failed construction; privacy has its own code.', ['DIA-14', 'MOD-2']),
'F-012': ('IMPL', '`print`/`println` are specified; an accepted program that yields bad C is a compiler defect, caught by the C gate.', ['STD-9', 'CG-C-2', 'TST-27']),
'F-013': ('GATE', 'Every accepted test program is compiled by each host C compiler with warnings as errors.', ['TST-27', 'CG-C-2']),
'F-014': ('SPEC', 'A name assigned in every branch at one type is declared after the branch.', ['CTL-10']),
'F-015': ('SPEC', '`if x = 5:` gets the `==` fix-it.', ['DIA-21']),
'F-016': ('SPEC', 'Pattern conditions are in the grammar; 0.9.9 carries no stale change log.', ['GRM-19']),
'F-017': ('SPEC', 'Part III is a complete grammar with no deleted productions.', ['GRM-11', 'GRM-16']),
'F-018': ('SPEC', 'One path separator, `.`; `::` is not a token.', ['GRM-24', 'LEX-21']),
'F-019': ('SPEC', 'Prefix `-`/`~` bind tighter than `as`.', ['TYP-6']),
'F-020': ('SPEC', '`@deprecated(since, note)` is the one form.', ['VER-3']),
'F-021': ('SPEC', '`@nopanic(explicit)` is a current contract; bare `@nopanic` is `E0104`.', ['EFF-17']),
'F-022': ('SPEC', 'Rule rewritten; no editorial instructions remain in rule text (end check).', ['BLD-11']),
'F-023': ('SPEC', '`E1020` means only a duplicate declaration; visibility errors are `E1052`.', ['GRM-4', 'MOD-2']),
'F-024': ('SPEC', '`Query` uses the ordinary marker type `Mut[T]`; no access-mode generic kind.', ['ECS-3']),
'F-025': ('SPEC', 'Ember has no lifetime syntax, now or later.', ['LEX-22']),
'F-026': ('SPEC', 'The formatter writes LF everywhere.', ['FMT-1']),
'F-027': ('SPEC', 'The reserved-word count is stated once, correctly.', ['LEX-15']),
'F-028': ('SPEC', 'The I.4 table states check mechanisms, not nanosecond promises.', ['PHIL-15']),
'F-029': ('IMPL', 'Explicit constructor type arguments fix the type.', ['TYP-18']),
'F-030': ('SPEC', '`min`, `max`, `abs`, `clamp` are prelude functions.', ['MOD-5']),
'F-031': ('SPEC', 'Literal-to-`String` coercion, `String + str`, `+=`, `to_string`.', ['TXT-9', 'TXT-11']),
'F-032': ('SPEC', 'One rule for where views may be stored; containers of static `str` are legal.', ['TYP-15']),
'F-033': ('SPEC', 'Shift amount checked; bits shifted out are not overflow; `>>` arithmetic on signed.', ['TYP-10']),
'F-034': ('SPEC', 'The niche list names `extern fn`, which exists.', ['TYP-13']),
'F-035': ('SPEC', '`as?` and `as!` are single tokens in the grammar.', ['GRM-30', 'LEX-21']),
'F-036': ('SPEC', 'View-ness is inferred; `@view` is optional documentation.', ['TYP-34']),
'F-037': ('SPEC', '`int` is `i64`, `float` is `f64`; literals default to them after context.', ['TYP-1', 'LEX-16']),
'F-038': ('SPEC', 'Floats implement `Ord` by totalOrder; operators stay IEEE; `sort()` works.', ['TYP-37']),
'F-039': ('SPEC', 'Each range rule is its own bullet.', ['RNG-10']),
'F-040': ('SPEC', 'Coherence is per package: an `extend` may sit in any module of the package declaring the type or interface.', ['TYP-20']),
'F-041': ('SPEC', 'Interface methods resolve without importing the interface when one visible implementation provides them.', ['TYP-24']),
'F-042': ('SPEC', 'A normative table of which built-in types implement which interfaces.', ['TYP-36']),
'F-043': ('SPEC', 'Comparison operators are built in for scalars and `Ord.cmp` in generic code; no `PartialOrd`.', ['TYP-37']),
'F-044': ('SPEC', '`Ordering` is in the prelude; `Formatter`, `FmtError` are declared in `std.fmt`.', ['MOD-5', 'STD-18']),
'F-045': ('SPEC', 'Three interfaces: `Iterator`, `Iterable`, `IntoIterator`; `iter_mut` is a method convention.', ['CTL-1', 'TYP-36']),
'F-046': ('SPEC', 'Before 1.0 there is one language; no version selectors.', ['VER-8']),
'F-047': ('SPEC', 'The prelude table is the single authoritative list.', ['MOD-5']),
'F-048': ('SPEC', '`Map` and `Set` are prelude names.', ['MOD-5']),
'F-049': ('SPEC', 'Comparisons chain with Python meaning; the middle operand is evaluated once.', ['GRM-25']),
'F-050': ('SPEC', '`a in b in c` is `E0102`.', ['GRM-23']),
'F-051': ('SPEC', '`extend [T: B] Array[T] implements I:` is in the grammar.', ['GRM-34']),
'F-052': ('SPEC', 'Inherent and interface extensions both follow package granularity.', ['IFC-1', 'TYP-20']),
'F-053': ('SPEC', 'Rules are written once; the rewritten parts carry no duplicates.', ['GRM-20', 'GRM-8d']),
'F-054': ('SPEC', '`Eq`, `Debug`, `Clone` are implicit when fields allow; `@no_derive` opts out.', ['STR-5']),
'F-055': ('SPEC', 'Statics may have run-time initialisers: lazy, once, thread-safe.', ['STA-1', 'STA-3']),
'F-056': ('SPEC', '`main(args: Array[String])` decodes lossily; raw bytes via `args_os()`.', ['FN-8']),
'F-057': ('SPEC', 'Examples either compile or are marked `ember,fragment`; math names are imported or methods.', ['TST-7']),
'F-058': ('SPEC', 'Callable types outside parameters are owned callable values; returning a closure is `-> fn(A) -> R`.', ['CLO-3', 'CLO-10']),
'F-059': ('SPEC', 'Position-dependent meaning of `fn(A) -> R` is specified.', ['CLO-3']),
'F-060': ('SPEC', '`b.on_click()` calls a callable field when no method of that name exists.', ['CLO-11']),
'F-061': ('SPEC', 'An owned `once fn`, boxed or not, is callable; the call consumes it.', ['CLO-6a']),
'F-062': ('SPEC', 'Class generator methods take `self`; no class long-term access spans a `yield`.', ['CORO-12']),
'F-063': ('SPEC', '`Generator[Y, R]` names both the yield and the return type.', ['CORO-1']),
'F-064': ('SPEC', 'Temporaries of an `if` condition are dropped before `else`.', ['EXP-4']),
'F-065': ('SPEC', '`%` and `//` have Python floor semantics; `rem_trunc`/`div_trunc` give C\'s.', ['TYP-28']),
'F-066': ('SPEC', '`**` on integers: negative exponent panics (constant: `E2151`); overflow panics.', ['TYP-30']),
'F-067': ('SPEC', 'Private methods borrow only the fields they touch.', ['BRW-10']),
'F-068': ('SPEC', 'Unparenthesised tuples on the right of `=` and after `return`.', ['GRM-29']),
'F-069': ('WDN', 'Withdrawn: premise disproved by probe (see F-168).', []),
'F-070': ('SPEC', 'Arena elision: a view returned from a function whose only view source is one `Arena` borrows it.', ['LT-44']),
'F-071': ('SPEC', '`@borrows` stands on its own line; the example no longer contradicts it.', ['LT-1a']),
'F-072': ('SPEC', 'A panic in `drop` aborts; stated as behaviour, not an unenforceable obligation.', ['DRP-4']),
'F-073': ('SPEC', 'Class fields are written through `self` or any handle without `mut`; each access is checked.', ['CLS-7', 'FN-9']),
'F-074': ('SPEC', 'Opaque `some I` returns and generators.', ['TYP-32', 'CORO-1']),
'F-075': ('SPEC', 'One API name: `split_at`.', ['SPN-5']),
'F-076': ('SPEC', 'The example is inside `main`.', ['GRM-2']),
'F-077': ('SPEC', 'The APIs examples use are specified in Part XV.', ['STD-15', 'STD-19']),
'F-078': ('SPEC', 'Only `@sync` classes are shareable, and their fields are immutable after `init`; no data race.', ['THR-1', 'THR-13']),
'F-079': ('SPEC', 'Assigning a non-`Copy` field through a handle is a write access.', ['EXC-16']),
'F-080': ('SPEC', '`String.from(s)`, `s.to_string()` and literal coercion are specified.', ['TXT-9', 'TXT-11']),
'F-081': ('SPEC', 'Borrowed class-handle parameters may be written through.', ['CLS-7', 'FN-9']),
'F-082': ('SPEC', 'Debug runs report leaked cycles at exit by default.', ['WK-15']),
'F-083': ('SPEC', 'Early deinitialisation is specified with `with h:` and lint `L3019`.', ['RC-3']),
'F-084': ('SPEC', 'Callable fields, pattern conditions and owned callable values make the idiom writable.', ['CLO-3', 'CLO-11']),
'F-085': ('GATE', 'Every `ember` block of the current document is extracted and checked.', ['TST-7']),
'F-086': ('SPEC', '`FixedArena` is the `@noalloc` arena type; `Arena.fixed` returns it.', ['ARN-4']),
'F-087': ('SPEC', 'Kept, with the selection table saying when each applies.', ['SEL-1']),
'F-088': ('IMPL', 'The heap library is specified; building it is implementation work.', ['HEAP-1', 'STD-15', 'STD-16']),
'F-089': ('SPEC', 'Safety notes are the one stated exception to "comments never affect compilation".', ['LEX-11', 'LEX-23', 'UNS-8']),
'F-090': ('SPEC', '`assert_disjoint` returns a `Result` that gives the views back on failure.', ['DSJ-1']),
'F-091': ('SPEC', 'The global allocator is named in the manifest; no unsized static.', ['ALC-3']),
'F-092': ('SPEC', 'Phantom type parameters are legal.', ['TYP-35']),
'F-093': ('SPEC', '`Map`/`Set` iterate in insertion order and are not `Nondet`.', ['STD-11', 'DET-2']),
'F-094': ('SPEC', 'Fixed-seed `DefaultHasher`; `RandomState` for untrusted keys.', ['HASH-2']),
'F-095': ('SPEC', 'Callable parameters contribute the passed function\'s effects, per instantiation.', ['EFF-2']),
'F-096': ('SPEC', 'Four `RuntimeCheck` kinds, named.', ['EFF-9']),
'F-097': ('SPEC', 'What `@nopanic(explicit)` allows is stated plainly.', ['EFF-16']),
'F-098': ('SPEC', '`RuntimeCheck` is allowed under `@nopanic(explicit)` and `@realtime`; `NonZero` removes division checks.', ['EFF-16', 'EFF-19', 'STD-4']),
'F-099': ('SPEC', 'The attribute table lists `@nopanic(explicit)`.', ['ATT-1']),
'F-100': ('GATE', 'Single-file programs need no manifest; the user guide and first-week corpus are release artefacts.', ['CLI-4', 'DOC-2', 'TST-8']),
'F-101': ('SPEC', 'Stale-handle checks run in every profile.', ['HND-1', 'COST-3']),
'F-102': ('SPEC', 'Overflow panics in every profile; the emitted C is UB-free.', ['TYP-8', 'CG-C-1']),
'F-103': ('SPEC', 'Toolchain rules live in Part XVII.', ['CLI-4']),
'F-104': ('SPEC', 'Plain mutable fields cannot exist in a `@sync` class.', ['THR-1']),
'F-105': ('SPEC', 'The job example uses a scope, borrows legally, and writes no call-site modes.', ['JOB-2', 'FN-2a']),
'F-106': ('SPEC', 'A scope is a `with` block; jumps keep their meaning and join first.', ['THR-5']),
'F-107': ('SPEC', '`async` stays reserved; generators are designed not to block it.', ['LEX-15']),
'F-108': ('SPEC', 'Compile-time code may allocate.', ['CT-1']),
'F-109': ('SPEC', 'Heap results are read-only static data, run-time initialised, or cloned per evaluation.', ['CT-5']),
'F-110': ('SPEC', '`comptime(e)` is the expression form.', ['CT-6', 'GRM-32']),
'F-111': ('SPEC', 'Examples use grammar that exists: proxies are `SoARef`, `@from` is on the variant, no call-site `mut`.', ['SOA-6', 'ERR-3', 'FN-2a']),
'F-112': ('SPEC', '`SoA[T]` is a compiler-known type constructor.', ['SOA-1']),
'F-113': ('SPEC', '`Result[T, E = AnyError]`.', ['ERR-9', 'ERR-8']),
'F-114': ('SPEC', 'The spec text itself defines what each derive generates.', ['DRV-1']),
'F-115': ('SPEC', 'Conformance profiles put the core language and C before C++; C++ is an optional annex.', ['CONF-2', 'CONF-4']),
'F-116': ('SPEC', 'Prelude has `min`/`max`/`abs`/`clamp`; `sqrt` is a method; other math is imported.', ['MOD-5', 'STD-20']),
'F-117': ('SPEC', 'The mandated help is Ember syntax.', ['STD-8']),
'F-118': ('SPEC', 'Conversions from foreign text are fallible `to_str()`.', ['TXT-2']),
'F-119': ('SPEC', '`print`/`println` signature, `sep=`, `end=`, several arguments.', ['STD-9', 'TYP-26']),
'F-120': ('SPEC', 'No `unsafe(reason=…)`; the category goes in the `# SAFETY(…):` note.', ['LEX-23', 'UNS-8']),
'F-121': ('SPEC', 'Each rule sits in its Part.', ['STD-4']),
'F-122': ('SPEC', 'The prelude table includes them.', ['MOD-5']),
'F-123': ('SPEC', 'Manual declarations are module items; a function declared `safe fn` with a complete contract is safe to call (an asserted fact).', ['FFI-10']),
'F-124': ('SPEC', 'Rewritten without editorial instructions; grades move to Annex C.', ['TCB-1']),
'F-125': ('SPEC', '`CppString.to_str()` everywhere.', ['FFI-17a']),
'F-126': ('SPEC', 'The overlay language has a grammar.', ['GRM-35']),
'F-127': ('SPEC', 'C++ is an optional annex after C.', ['CONF-4', 'FFI-3']),
'F-128': ('SPEC', 'The count axis is listed: `one`, `count(n)`, `nul_terminated`, `fixed(N)`, `inout_count(p)`.', ['FFI-11', 'FFI-11a']),
'F-129': ('SPEC', 'Constructors are `fn init(self, …)` everywhere, including C++ subclasses.', ['FFI-39', 'CLS-2']),
'F-130': ('SPEC', 'No setting removes a safety check; the two keys are gone.', ['PRF-1', 'EXC-14', 'GPU-1']),
'F-131': ('SPEC', 'No call-site modes in examples.', ['FN-2a']),
'F-132': ('SPEC', 'Refusal reports do not suggest signatures; `migrate_from` returns `Result`.', ['HR-16', 'HR-18']),
'F-133': ('SPEC', 'Run-time check failures in `migrate_from` become `ReloadError.Migration`.', ['HR-35']),
'F-134': ('SPEC', 'A derived class with no `init` inherits its base\'s.', ['CLS-10']),
'F-135': ('SPEC', 'Citations rewritten; one attribute per line.', ['HR-3', 'ATT-4']),
'F-136': ('SPEC', 'Mangling is length-prefixed and injective; a hash collision is `E9040`.', ['MNG-1']),
'F-137': ('IMPL', '`for x in span:` iterates a `Span`.', ['CTL-1']),
'F-138': ('IMPL', 'The guaranteed counted-loop lowering stands.', ['CTL-3']),
'F-139': ('SPEC', 'Floating-point flags and pragmas are required of the backend.', ['CG-C-11', 'TYP-9']),
'F-140': ('GATE', 'A performance suite against equivalent C gates releases.', ['TST-28']),
'F-141': ('SPEC', 'Inline header, allocator and backtrace requirements restated; mimalloc no longer required.', ['CG-C-3', 'RT-1', 'CG-C-10']),
'F-142': ('OUT', 'Source-file size in the compiler is not language text; noted for the compiler.', []),
'F-143': ('SPEC', 'Effects are computed once, per instantiation for callable parameters.', ['EFF-2', 'EFF-15']),
'F-144': ('GATE', 'First-week corpus and published acceptance rate.', ['TST-8', 'TST-10']),
'F-145': ('SPEC', '`E9010` is an unknown manifest key; an unhonourable float attribute is `E9041`.', ['MAN-1', 'TYP-9c']),
'F-146': ('SPEC', 'The CLI is listed; anything unimplemented is `E0900` and shown by `--matrix`.', ['CLI-19']),
'F-147': ('SPEC', 'The manifest example has no safety keys; none exist.', ['MAN-8']),
'F-148': ('SPEC', 'Indices are `int`; a negative literal index is `E2011`; a negative index panics with a clear message.', ['TYP-31', 'LEX-24']),
'F-149': ('SPEC', '`x is None` is legal.', ['EXP-9']),
'F-150': ('SPEC', '`let x = 5` gets the `x = 5` fix-it.', ['DIA-21']),
'F-151': ('SPEC', 'Chained comparisons are legal, so no fix-it is needed.', ['GRM-25']),
'F-152': ('SPEC', 'Diagnostic tables are real tables.', ['DIA-7']),
'F-153': ('SPEC', 'Suggestion distance: 1 up to 4 characters, 2 above.', ['DIA-24']),
'F-154': ('SPEC', 'Shape table rewritten; N8 no longer asks for a call-site mode.', ['DIA-7', 'FN-2a']),
'F-155': ('SPEC', 'Integer `/` is rejected with fix-its; `//` is floor division.', ['TYP-28']),
'F-156': ('GATE', 'User guide with a Python chapter ships each release; Appendix E is its basis.', ['DOC-2']),
'F-157': ('SPEC', 'One C++ exception policy, with a default.', ['FFI-24']),
'F-158': ('SPEC', 'Rewritten without appended amendments.', ['TCB-1']),
'F-159': ('OUT', 'Phase status is project tracking; `ember --version --matrix` makes implementation status visible.', ['CLI-19']),
'F-160': ('IMPL', 'Indexing yields a place; a `ref` result auto-borrows it.', ['TYP-5', 'GRM-36']),
'F-161': ('SPEC', 'Unbuilt contracts and unknown attributes are rejected, never ignored.', ['PHIL-12', 'EFF-23']),
'F-162': ('SPEC', '`mem` is in the prelude.', ['MOD-5']),
'F-163': ('SPEC', 'The user guide is a release artefact.', ['DOC-2']),
'F-164': ('OUT', 'The engine-specific Stage 0 example is outside the language document.', []),
'F-165': ('SPEC', 'New glossary and reserved-word statement.', ['LEX-15']),
'F-166': ('SPEC', 'Decided in this revision: 64-bit number defaults, branch-declared names, no `::`.', ['TYP-1', 'CTL-10', 'GRM-24']),
'F-167': ('GATE', 'Annex A is generated from a checked fixture.', ['TST-6']),
'F-168': ('SPEC', '`with_views*` and `@latebound` are removed; callable types get fresh regions per call.', ['LT-7']),
'F-169': ('SPEC', 'Diagnostics from a callee\'s contract point at the call site.', ['DIA-22']),
'F-170': ('SPEC', 'The multi-region example takes `mut b`.', ['FN-2a']),
'F-171': ('GATE', 'The implementation matrix is a compiler output.', ['CLI-19']),
'F-172': ('OUT', 'Part XXIV (compiler internals) is not in 0.9.9; its user-visible obligations are Part XVIII.', ['IMP-11']),
'F-173': ('OUT', '0.9.9 is the language document only; compiler design and history are elsewhere.', []),
'F-174': ('SPEC', 'One coherence rule, at package granularity.', ['TYP-20']),
'F-175': ('SPEC', '64-bit handles by default; exhausted slots retire; full pool is `CapacityError`.', ['HND-2', 'HND-3']),
'F-176': ('SPEC', 'Old images are never unloaded; statics live outside images.', ['HR-4', 'HR-4a']),
'F-177': ('OUT', 'No self-checking checklist in the document; the end checks are tools.', ['TST-4']),
'F-178': ('OUT', 'Appendix H is a change list, not audit records.', []),
'F-179': ('OUT', '1.0 is defined by conformance and gates, not by a host migration.', ['CONF-1']),
'F-180': ('IMPL', 'Conditional expressions are in the grammar.', ['GRM-11']),
'F-181': ('SPEC', 'Scalars implement `Ord`.', ['TYP-36']),
'F-182': ('IMPL', 'The combinator and container APIs are specified.', ['ERR-4', 'STD-15', 'TXT-10']),
'F-183': ('IMPL', 'A one-statement lambda body in brackets is legal.', ['GRM-17']),
'F-184': ('IMPL', 'Range types print and compile; the C gate catches broken C.', ['CG-C-2', 'TST-27']),
'F-185': ('IMPL', 'An internal compiler error is always a defect.', ['CG-C-2']),
'F-186': ('SPEC', 'Panics name Ember entities.', ['DIA-23', 'EXC-6']),
'F-187': ('SPEC', '`L3011` fires only for calls that can reach the cell.', ['CELL-7']),
'F-188': ('SPEC', 'Storage end with a live loan is one diagnostic, shape B7.', ['BCK-4', 'DIA-7']),
'F-189': ('IMPL', '`Array.iter()` is specified.', ['STD-15']),
'F-190': ('SPEC', 'Capacity arithmetic is checked.', ['HEAP-8']),
'F-191': ('SPEC', 'Heap storage honours element alignment.', ['HEAP-9']),
'F-192': ('SPEC', 'Layout attributes are honoured or rejected.', ['LAY-2', 'PHIL-12']),
'F-193': ('SPEC', 'Count fast paths are inline; a `@sync` retain is one `fetch_add`.', ['RT-10']),
'F-194': ('SPEC', 'System allocator for ordinary alignment; per-thread statistics.', ['RT-1', 'RT-11']),
'F-195': ('SPEC', 'Count overflow panics with its own message.', ['RT-7']),
'F-196': ('IMPL', 'Redeclaring in one block is `E1020`.', ['GRM-4']),
'F-197': ('IMPL', 'Raw strings and format specs are specified.', ['LEX-19', 'LEX-25']),
'F-198': ('SPEC', 'A table of Python habits with fix-its.', ['DIA-21', 'STD-13']),
'F-199': ('OUT', 'Defect ledgers are project process; Appendix G lists every open finding with its resolution.', []),
'F-200': ('OUT', 'Process: 0.9.9 consolidates to one revision and a smaller document.', []),
'F-201': ('OUT', 'Repository handoff size is not language text.', []),
'F-202': ('GATE', 'Documentation samples are compiled and run.', ['DOC-2']),
'F-203': ('SPEC', '`Self` and the type\'s own name work inside its declaration.', ['STR-7']),
'F-204': ('SPEC', '`Box[T]` reads through like a reference.', ['TYP-14']),
'F-205': ('SPEC', 'Callable bounds are written `F: fn(A) -> R`; `Callable[…]` is not source.', ['CLO-14']),
'F-206': ('GATE', 'Every code has an error page; a missing page fails CI.', ['DIA-6']),
'F-207': ('GATE', 'Baselines are reported and a heavily baselined gate is not called green.', ['TST-29']),
'F-208': ('IMPL', 'Slicing is specified; its failure must not cascade.', ['DIA-14']),
'F-209': ('SPEC', 'List, set and map comprehensions.', ['GRM-27']),
'F-210': ('SPEC', 'Interfaces stay nominal, with the reason stated.', ['TYP-40']),
'F-211': ('IMPL', '`enumerate` over an array is specified.', ['STD-19']),
'F-212': ('OUT', 'The errata ledger is outside the document.', []),
'F-213': ('SPEC', '`MIN % -1 == 0`; `MIN // -1` panics as overflow, naming the right operator.', ['TYP-28']),
'F-214': ('GATE', 'The runner reports all failures and quarantines flaky tests by name.', ['TST-30']),
}
